"""Banco inicial de Listening Practice: clips + preguntas."""

from dataclasses import dataclass

LEO_MANTA_AUDIO_URL = "/audio/leo-manta.mp3"
LEO_MANTA_CLIP_KEY = "leo-manta"
LEO_MANTA_CLIP_TITLE = "Listening 1: The Life of Leo"

DANIEL_SATURDAY_AUDIO_URL = "/audio/daniel-saturday.mp3"
DANIEL_SATURDAY_CLIP_KEY = "daniel-saturday"
DANIEL_SATURDAY_CLIP_TITLE = "Listening 2: A Different Saturday"

EMILY_PHOTOGRAPHY_AUDIO_URL = "/audio/emily-photography.mp3"
EMILY_PHOTOGRAPHY_CLIP_KEY = "emily-photography"
EMILY_PHOTOGRAPHY_CLIP_TITLE = "Listening 3: My Favorite Hobby"

EMMA_WEEKEND_AUDIO_URL = "/audio/emma-weekend.mp3"
EMMA_WEEKEND_CLIP_KEY = "emma-weekend"
EMMA_WEEKEND_CLIP_TITLE = "Listening Exam 1: Emma's Weekend"

MARCUS_ENGLISH_AUDIO_URL = "/audio/marcus-english.mp3"
MARCUS_ENGLISH_CLIP_KEY = "marcus-english"
MARCUS_ENGLISH_CLIP_TITLE = "Listening Exam 2: Learning English"
LISTENING_EXAM_QUESTION_COUNT = 22


@dataclass(frozen=True)
class ListeningClipSeed:
    clip_key: str
    title: str
    description: str
    audio_url: str
    sort_order: int = 1


LISTENING_CLIPS: list[ListeningClipSeed] = [
    ListeningClipSeed(
        clip_key=LEO_MANTA_CLIP_KEY,
        title=LEO_MANTA_CLIP_TITLE,
        description=(
            "Leo talks about his life in Manta, a Saturday at the beach, "
            "and the sports he has tried. You will hear Present Simple, "
            "Past Simple and Present Perfect."
        ),
        audio_url=LEO_MANTA_AUDIO_URL,
        sort_order=1,
    ),
    ListeningClipSeed(
        clip_key=DANIEL_SATURDAY_CLIP_KEY,
        title=DANIEL_SATURDAY_CLIP_TITLE,
        description=(
            "Daniel talks about his usual school day and a Saturday at the "
            "beach with his family. You will hear Present Simple, Past Simple "
            "and Present Perfect."
        ),
        audio_url=DANIEL_SATURDAY_AUDIO_URL,
        sort_order=2,
    ),
    ListeningClipSeed(
        clip_key=EMILY_PHOTOGRAPHY_CLIP_KEY,
        title=EMILY_PHOTOGRAPHY_CLIP_TITLE,
        description=(
            "Emily talks about photography, a trip to the mountains, "
            "and a competition she has not entered yet. You will hear "
            "Present Simple, Past Simple and Present Perfect."
        ),
        audio_url=EMILY_PHOTOGRAPHY_AUDIO_URL,
        sort_order=3,
    ),
]

LISTENING_EXAM_CLIPS: list[ListeningClipSeed] = [
    ListeningClipSeed(
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        title=EMMA_WEEKEND_CLIP_TITLE,
        description=(
            "Emma talks about her weekly routine and a weekend visit to her "
            "aunt in the countryside. You will hear Present Simple, Past "
            "Simple and Present Perfect."
        ),
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        sort_order=1,
    ),
    ListeningClipSeed(
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        title=MARCUS_ENGLISH_CLIP_TITLE,
        description=(
            "Marcus talks about studying computer science, learning English, "
            "and helping a tourist. You will hear Present Simple, Past Simple "
            "and Present Perfect."
        ),
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        sort_order=2,
    ),
]


@dataclass(frozen=True)
class ListeningQuestionSeed:
    stable_key: str
    topic: str
    question_type: str
    instruction: str
    question: str
    options: list[str] | None
    correct_answer: str
    accepted_answers: list[str]
    explanation: str
    audio_url: str = LEO_MANTA_AUDIO_URL
    clip_key: str = LEO_MANTA_CLIP_KEY
    clip_title: str = LEO_MANTA_CLIP_TITLE
    points: int = 1
    active: bool = True


LISTENING_QUESTIONS: list[ListeningQuestionSeed] = [
    ListeningQuestionSeed(
        stable_key="listening_leo_manta_01_live",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Where does Leo live?",
        options=["Quito", "Guayaquil", "Manta", "Cuenca"],
        correct_answer="Manta",
        accepted_answers=["in Manta", "He lives in Manta."],
        explanation="Leo says: 'I live in Manta with my parents.'",
    ),
    ListeningQuestionSeed(
        stable_key="listening_leo_manta_02_english",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="How often does Leo study English?",
        options=[
            "every day",
            "three times a week",
            "once a month",
            "only on weekends",
        ],
        correct_answer="three times a week",
        accepted_answers=["3 times a week", "three times a week."],
        explanation="Leo says he studies English three times a week.",
    ),
    ListeningQuestionSeed(
        stable_key="listening_leo_manta_03_wake_up",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What time does Leo usually wake up?",
        options=[
            "at five o'clock",
            "at six thirty",
            "at seven o'clock",
            "at eight fifteen",
        ],
        correct_answer="at six thirty",
        accepted_answers=[
            "six thirty",
            "6:30",
            "6.30",
            "at 6:30",
            "at 6.30",
        ],
        explanation="Leo usually wakes up at six thirty.",
    ),
    ListeningQuestionSeed(
        stable_key="listening_leo_manta_04_bus",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="How does Leo go to school?",
        options=[
            "He walks to school.",
            "He takes the bus to school.",
            "His parents drive him to school.",
            "He rides a bike to school.",
        ],
        correct_answer="He takes the bus to school.",
        accepted_answers=["by bus", "He takes the bus.", "take the bus"],
        explanation="After breakfast, Leo takes the bus to school.",
    ),
    ListeningQuestionSeed(
        stable_key="listening_leo_manta_05_free_time",
        topic="detail",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What does Leo do in his free time?",
        options=[
            "He plays soccer and reads books.",
            "He plays volleyball and watches movies with his friends.",
            "He goes swimming and studies math.",
            "He plays tennis and cooks with his parents.",
        ],
        correct_answer="He plays volleyball and watches movies with his friends.",
        accepted_answers=[
            "play volleyball and watch movies",
            "volleyball and movies",
        ],
        explanation=(
            "In his free time, Leo plays volleyball and watches movies with his friends."
        ),
    ),
    ListeningQuestionSeed(
        stable_key="listening_leo_manta_06_saturday",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What happened last Saturday?",
        options=[
            "Leo stayed at home all day.",
            "Leo's cousin invited him to the beach.",
            "Leo had an English exam.",
            "Leo visited Quito with his parents.",
        ],
        correct_answer="Leo's cousin invited him to the beach.",
        accepted_answers=[
            "His cousin invited him to the beach.",
            "His cousin invited him to the beach",
        ],
        explanation="Last Saturday was different because Leo's cousin invited him to the beach.",
    ),
    ListeningQuestionSeed(
        stable_key="listening_leo_manta_07_surfing",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What new sport did Leo try at the beach?",
        options=["basketball", "tennis", "surfing", "soccer"],
        correct_answer="surfing",
        accepted_answers=["surf", "to surf", "He tried surfing."],
        explanation="Leo's cousin asked him to try surfing.",
    ),
    ListeningQuestionSeed(
        stable_key="listening_leo_manta_08_nervous",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="How did Leo feel at first about surfing?",
        options=["bored", "angry", "nervous", "confident"],
        correct_answer="nervous",
        accepted_answers=["He was nervous.", "nervous."],
        explanation="Leo says: 'At first, I was nervous, but I tried it.'",
    ),
    ListeningQuestionSeed(
        stable_key="listening_leo_manta_09_never_surfed",
        topic="present_perfect",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Had Leo ever surfed before that day?",
        options=[
            "Yes, he surfs every weekend.",
            "Yes, he had surfed once before.",
            "No, he had never surfed before that day.",
            "He does not remember.",
        ],
        correct_answer="No, he had never surfed before that day.",
        accepted_answers=["No", "never", "He has never surfed."],
        explanation="Leo has tried many sports, but he had never surfed before that day.",
    ),
    ListeningQuestionSeed(
        stable_key="listening_leo_manta_10_never_won",
        topic="present_perfect",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Has Leo ever won a sports competition?",
        options=[
            "Yes, two volleyball competitions.",
            "Yes, a tennis competition.",
            "No, he has never won a competition.",
            "Yes, a surfing competition.",
        ],
        correct_answer="No, he has never won a competition.",
        accepted_answers=["No", "never", "He has never won."],
        explanation=(
            "Leo has participated in two volleyball competitions, "
            "but he has never won a competition."
        ),
    ),
    ListeningQuestionSeed(
        stable_key="listening_daniel_saturday_01_live",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Who does Daniel live with?",
        options=[
            "his parents",
            "his mother and his younger brother",
            "his cousins",
            "his father and his sister",
        ],
        correct_answer="his mother and his younger brother",
        accepted_answers=[
            "his mom and his brother",
            "his mother and brother",
            "He lives with his mother and his younger brother.",
        ],
        explanation="Daniel lives with his mother and his younger brother.",
        audio_url=DANIEL_SATURDAY_AUDIO_URL,
        clip_key=DANIEL_SATURDAY_CLIP_KEY,
        clip_title=DANIEL_SATURDAY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_daniel_saturday_02_wake_up",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What time does Daniel usually wake up?",
        options=[
            "at six thirty",
            "at seven o'clock",
            "at eight o'clock",
            "at five o'clock",
        ],
        correct_answer="at seven o'clock",
        accepted_answers=["seven", "7:00", "at 7", "at seven"],
        explanation="Daniel usually wakes up at seven in the morning.",
        audio_url=DANIEL_SATURDAY_AUDIO_URL,
        clip_key=DANIEL_SATURDAY_CLIP_KEY,
        clip_title=DANIEL_SATURDAY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_daniel_saturday_03_breakfast",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What does Daniel do before he goes to school?",
        options=[
            "He plays basketball.",
            "He has breakfast.",
            "He goes to the beach.",
            "He does his homework.",
        ],
        correct_answer="He has breakfast.",
        accepted_answers=["have breakfast", "He has breakfast", "breakfast"],
        explanation="Daniel has breakfast before he goes to school.",
        audio_url=DANIEL_SATURDAY_AUDIO_URL,
        clip_key=DANIEL_SATURDAY_CLIP_KEY,
        clip_title=DANIEL_SATURDAY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_daniel_saturday_04_after_school",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What does Daniel normally do after school?",
        options=[
            "He plays volleyball.",
            "He plays basketball with his friends.",
            "He goes surfing.",
            "He stays at home and watches movies.",
        ],
        correct_answer="He plays basketball with his friends.",
        accepted_answers=[
            "play basketball",
            "He plays basketball.",
            "basketball with his friends",
        ],
        explanation="After school, Daniel normally plays basketball with his friends.",
        audio_url=DANIEL_SATURDAY_AUDIO_URL,
        clip_key=DANIEL_SATURDAY_CLIP_KEY,
        clip_title=DANIEL_SATURDAY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_daniel_saturday_05_saturday",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What did Daniel and his family do last Saturday?",
        options=[
            "They stayed at home.",
            "They went to the beach.",
            "They visited a museum.",
            "They played basketball at school.",
        ],
        correct_answer="They went to the beach.",
        accepted_answers=["went to the beach", "They went to the beach"],
        explanation="Last Saturday, Daniel's family went to the beach.",
        audio_url=DANIEL_SATURDAY_AUDIO_URL,
        clip_key=DANIEL_SATURDAY_CLIP_KEY,
        clip_title=DANIEL_SATURDAY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_daniel_saturday_06_arrived",
        topic="detail",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="When did they arrive at the beach?",
        options=[
            "late in the afternoon",
            "at night",
            "early in the morning",
            "after lunch",
        ],
        correct_answer="early in the morning",
        accepted_answers=["early", "in the morning", "early morning"],
        explanation="They arrived early in the morning.",
        audio_url=DANIEL_SATURDAY_AUDIO_URL,
        clip_key=DANIEL_SATURDAY_CLIP_KEY,
        clip_title=DANIEL_SATURDAY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_daniel_saturday_07_activities",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What did they do at the beach?",
        options=[
            "They played soccer and ate dinner.",
            "They played volleyball and ate lunch near the sea.",
            "They went kayaking and swimming.",
            "They studied English.",
        ],
        correct_answer="They played volleyball and ate lunch near the sea.",
        accepted_answers=[
            "played volleyball and ate lunch",
            "volleyball and lunch",
        ],
        explanation="They played volleyball and ate lunch near the sea.",
        audio_url=DANIEL_SATURDAY_AUDIO_URL,
        clip_key=DANIEL_SATURDAY_CLIP_KEY,
        clip_title=DANIEL_SATURDAY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_daniel_saturday_08_surfing",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Who tried surfing for the first time?",
        options=[
            "Daniel",
            "Daniel's mother",
            "Daniel's younger brother",
            "Daniel's friends",
        ],
        correct_answer="Daniel's younger brother",
        accepted_answers=[
            "his brother",
            "his younger brother",
            "Daniel's brother",
        ],
        explanation="Daniel's brother tried surfing for the first time.",
        audio_url=DANIEL_SATURDAY_AUDIO_URL,
        clip_key=DANIEL_SATURDAY_CLIP_KEY,
        clip_title=DANIEL_SATURDAY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_daniel_saturday_09_never_surfed",
        topic="present_perfect",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Has Daniel ever tried surfing?",
        options=[
            "Yes, he surfs every weekend.",
            "Yes, he tried it last Saturday.",
            "No, he has never tried surfing.",
            "He tried it once last year.",
        ],
        correct_answer="No, he has never tried surfing.",
        accepted_answers=["No", "never", "He has never tried surfing."],
        explanation="Daniel has been to the beach many times, but he has never tried surfing.",
        audio_url=DANIEL_SATURDAY_AUDIO_URL,
        clip_key=DANIEL_SATURDAY_CLIP_KEY,
        clip_title=DANIEL_SATURDAY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_daniel_saturday_10_water",
        topic="present_perfect",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Which water activities has Daniel tried?",
        options=[
            "surfing and kayaking",
            "kayaking and swimming",
            "swimming and diving",
            "surfing and swimming",
        ],
        correct_answer="kayaking and swimming",
        accepted_answers=["kayaking and swimming.", "kayak and swim"],
        explanation="Daniel has tried kayaking and swimming.",
        audio_url=DANIEL_SATURDAY_AUDIO_URL,
        clip_key=DANIEL_SATURDAY_CLIP_KEY,
        clip_title=DANIEL_SATURDAY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emily_photography_01_hobby",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What does Emily love?",
        options=["painting", "photography", "dancing", "cooking"],
        correct_answer="photography",
        accepted_answers=["taking pictures", "photos", "She loves photography."],
        explanation="Emily says: 'I love photography.'",
        audio_url=EMILY_PHOTOGRAPHY_AUDIO_URL,
        clip_key=EMILY_PHOTOGRAPHY_CLIP_KEY,
        clip_title=EMILY_PHOTOGRAPHY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emily_photography_02_phone",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What does Emily usually use to take pictures?",
        options=[
            "her father's camera",
            "her phone",
            "a school camera",
            "her brother's laptop",
        ],
        correct_answer="her phone",
        accepted_answers=["her cellphone", "her mobile phone", "a phone"],
        explanation="Emily usually takes pictures with her phone.",
        audio_url=EMILY_PHOTOGRAPHY_AUDIO_URL,
        clip_key=EMILY_PHOTOGRAPHY_CLIP_KEY,
        clip_title=EMILY_PHOTOGRAPHY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emily_photography_03_camera",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Whose camera does Emily sometimes use?",
        options=[
            "her teacher's camera",
            "her friend's camera",
            "her father's camera",
            "her mother's camera",
        ],
        correct_answer="her father's camera",
        accepted_answers=["her dad's camera", "her father's"],
        explanation="Sometimes Emily uses her father's camera.",
        audio_url=EMILY_PHOTOGRAPHY_AUDIO_URL,
        clip_key=EMILY_PHOTOGRAPHY_CLIP_KEY,
        clip_title=EMILY_PHOTOGRAPHY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emily_photography_04_subjects",
        topic="detail",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What does Emily like taking pictures of?",
        options=[
            "cars, buildings, and food",
            "animals, sunsets, and her friends",
            "sports, schools, and cities",
            "flowers, beaches, and her family",
        ],
        correct_answer="animals, sunsets, and her friends",
        accepted_answers=["animals, sunsets, and friends"],
        explanation="Emily likes taking pictures of animals, sunsets, and her friends.",
        audio_url=EMILY_PHOTOGRAPHY_AUDIO_URL,
        clip_key=EMILY_PHOTOGRAPHY_CLIP_KEY,
        clip_title=EMILY_PHOTOGRAPHY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emily_photography_05_trip",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Where did Emily's family travel last month?",
        options=[
            "to the beach",
            "to the mountains",
            "to another city",
            "to a photography museum",
        ],
        correct_answer="to the mountains",
        accepted_answers=["the mountains", "They traveled to the mountains."],
        explanation="Last month, Emily's family traveled to the mountains.",
        audio_url=EMILY_PHOTOGRAPHY_AUDIO_URL,
        clip_key=EMILY_PHOTOGRAPHY_CLIP_KEY,
        clip_title=EMILY_PHOTOGRAPHY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emily_photography_06_hundred",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="How many photos did Emily take during the trip?",
        options=[
            "fewer than fifty",
            "exactly one hundred",
            "more than one hundred",
            "about ten",
        ],
        correct_answer="more than one hundred",
        accepted_answers=["more than 100", "over one hundred"],
        explanation="Emily took more than one hundred photos during the trip.",
        audio_url=EMILY_PHOTOGRAPHY_AUDIO_URL,
        clip_key=EMILY_PHOTOGRAPHY_CLIP_KEY,
        clip_title=EMILY_PHOTOGRAPHY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emily_photography_07_sunrise",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What did they watch one morning?",
        options=["the sunset", "the sunrise", "a movie", "the rain"],
        correct_answer="the sunrise",
        accepted_answers=["sunrise", "They watched the sunrise."],
        explanation="One morning they woke up very early and watched the sunrise.",
        audio_url=EMILY_PHOTOGRAPHY_AUDIO_URL,
        clip_key=EMILY_PHOTOGRAPHY_CLIP_KEY,
        clip_title=EMILY_PHOTOGRAPHY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emily_photography_08_thousands",
        topic="present_perfect",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="How many photos has Emily taken in her life?",
        options=["about one hundred", "thousands", "only a few", "none"],
        correct_answer="thousands",
        accepted_answers=["thousands of photos", "She has taken thousands of photos."],
        explanation="Emily has taken thousands of photos in her life.",
        audio_url=EMILY_PHOTOGRAPHY_AUDIO_URL,
        clip_key=EMILY_PHOTOGRAPHY_CLIP_KEY,
        clip_title=EMILY_PHOTOGRAPHY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emily_photography_09_competition",
        topic="present_perfect",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Has Emily ever entered a photography competition?",
        options=[
            "Yes, she won last year.",
            "Yes, she entered one last month.",
            "No, she has never entered a photography competition.",
            "She enters competitions every year.",
        ],
        correct_answer="No, she has never entered a photography competition.",
        accepted_answers=["No", "never", "She has never entered a competition."],
        explanation="Emily has never entered a photography competition.",
        audio_url=EMILY_PHOTOGRAPHY_AUDIO_URL,
        clip_key=EMILY_PHOTOGRAPHY_CLIP_KEY,
        clip_title=EMILY_PHOTOGRAPHY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emily_photography_10_teacher",
        topic="present_perfect",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What has Emily's teacher told her?",
        options=[
            "She should stop taking photos.",
            "Some of her photos are very good.",
            "She must buy a new camera.",
            "She has already won a competition.",
        ],
        correct_answer="Some of her photos are very good.",
        accepted_answers=[
            "her photos are very good",
            "some of her photos are good",
        ],
        explanation="Emily's teacher has told her that some of her photos are very good.",
        audio_url=EMILY_PHOTOGRAPHY_AUDIO_URL,
        clip_key=EMILY_PHOTOGRAPHY_CLIP_KEY,
        clip_title=EMILY_PHOTOGRAPHY_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_01_age",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="How old is Emma?",
        options=["fifteen", "sixteen", "seventeen", "eighteen"],
        correct_answer="seventeen",
        accepted_answers=["17", "seventeen years old", "She is seventeen."],
        explanation="Emma says: 'I am seventeen years old.'",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_02_family",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Who does Emma live with?",
        options=[
            "her parents",
            "her parents and her younger sister",
            "her aunt and her cousins",
            "her mother and her older brother",
        ],
        correct_answer="her parents and her younger sister",
        accepted_answers=[
            "her parents and sister",
            "She lives with her parents and her younger sister.",
        ],
        explanation="Emma lives with her parents and her younger sister.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_03_city",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Where does Emma live?",
        options=[
            "on a farm in the countryside",
            "in a big city far from the sea",
            "in a small city near the coast",
            "in another country",
        ],
        correct_answer="in a small city near the coast",
        accepted_answers=["a small city near the coast", "near the coast"],
        explanation="Emma lives in a small city near the coast.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_04_wake_up",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What time does Emma wake up every morning?",
        options=[
            "at six o'clock",
            "at six thirty",
            "at seven o'clock",
            "at eight o'clock",
        ],
        correct_answer="at six thirty",
        accepted_answers=["six thirty", "6:30", "at 6:30", "6.30"],
        explanation="Emma wakes up at six thirty every morning.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_05_classes",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="When do Emma's school classes start and finish?",
        options=[
            "They start at seven and finish at one.",
            "They start at eight and finish at two in the afternoon.",
            "They start at eight thirty and finish at three.",
            "They start at nine and finish at two.",
        ],
        correct_answer="They start at eight and finish at two in the afternoon.",
        accepted_answers=[
            "8 to 2",
            "start at eight and finish at two",
            "from eight to two",
        ],
        explanation="Her classes start at eight o'clock and finish at two in the afternoon.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_06_english",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="When does Emma attend English classes?",
        options=[
            "Tuesdays and Thursdays",
            "Mondays and Wednesdays",
            "Fridays only",
            "every weekend",
        ],
        correct_answer="Mondays and Wednesdays",
        accepted_answers=["Monday and Wednesday", "on Mondays and Wednesdays"],
        explanation="On Mondays and Wednesdays, Emma attends English classes.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_07_volleyball",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="When does Emma play volleyball?",
        options=[
            "Mondays and Wednesdays",
            "Tuesdays and Thursdays",
            "Fridays after class",
            "Saturdays and Sundays",
        ],
        correct_answer="Tuesdays and Thursdays",
        accepted_answers=["Tuesday and Thursday", "on Tuesdays and Thursdays"],
        explanation="On Tuesdays and Thursdays, Emma plays volleyball with some friends from school.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_08_friday",
        topic="detail",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Why is Friday usually Emma's favorite day?",
        options=[
            "She has English class after school.",
            "She plays volleyball with her friends.",
            "She doesn't have any activities after class.",
            "She visits her aunt in the countryside.",
        ],
        correct_answer="She doesn't have any activities after class.",
        accepted_answers=[
            "no activities after class",
            "She does not have any activities after class.",
        ],
        explanation="Friday is her favorite day because she doesn't have any activities after class.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_09_weekend",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Where did Emma's family go last weekend?",
        options=[
            "to the beach",
            "to her aunt's house in the countryside",
            "to a farm in another country",
            "to an English class in the city",
        ],
        correct_answer="to her aunt's house in the countryside",
        accepted_answers=[
            "her aunt's house",
            "the countryside",
            "They visited her aunt.",
        ],
        explanation="Emma's aunt invited the family to visit her house in the countryside.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_10_travel",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="How long did they travel by car?",
        options=[
            "about thirty minutes",
            "almost one hour",
            "almost three hours",
            "all day",
        ],
        correct_answer="almost three hours",
        accepted_answers=["almost 3 hours", "three hours", "for almost three hours"],
        explanation="They traveled for almost three hours by car.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_11_breakfast",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What did Emma's aunt prepare when they arrived?",
        options=[
            "a picnic near the river",
            "homemade bread",
            "a big breakfast",
            "a comedy movie",
        ],
        correct_answer="a big breakfast",
        accepted_answers=["big breakfast", "She prepared a big breakfast."],
        explanation="When they arrived, Emma's aunt prepared a big breakfast for everyone.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_12_walk",
        topic="detail",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="How long did they walk before they reached the river?",
        options=[
            "about ten minutes",
            "about thirty minutes",
            "about an hour",
            "almost three hours",
        ],
        correct_answer="about thirty minutes",
        accepted_answers=["thirty minutes", "30 minutes", "about 30 minutes"],
        explanation="They walked for about thirty minutes before they reached the river.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_13_sister",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Why didn't Emma's younger sister want to enter the water?",
        options=[
            "The weather was cold.",
            "She was tired from the walk.",
            "She was scared.",
            "She wanted to ride a bicycle.",
        ],
        correct_answer="She was scared.",
        accepted_answers=["scared", "she was scared", "She didn't want to because she was scared."],
        explanation="Emma's younger sister didn't want to enter the water because she was scared.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_14_father",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Who convinced Emma's sister to try swimming?",
        options=["her aunt", "her cousins", "her father", "Emma"],
        correct_answer="her father",
        accepted_answers=["Emma's father", "her dad", "the father"],
        explanation="Eventually Emma's father convinced her sister to try.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_15_picnic",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What did they do after they swam for about an hour?",
        options=[
            "They rode bicycles to a farm.",
            "They had a picnic near the river.",
            "They made homemade bread.",
            "They watched a comedy movie.",
        ],
        correct_answer="They had a picnic near the river.",
        accepted_answers=["had a picnic", "a picnic near the river"],
        explanation="They swam for about an hour and then had a picnic near the river.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_16_animals",
        topic="detail",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What animals did they see at the farm?",
        options=[
            "horses, cows, chickens, and several dogs",
            "cats, sheep, ducks, and a goat",
            "only horses and cows",
            "birds, fish, and rabbits",
        ],
        correct_answer="horses, cows, chickens, and several dogs",
        accepted_answers=[
            "horses, cows, chickens, and dogs",
            "horses cows chickens dogs",
        ],
        explanation="At the farm, they saw horses, cows, chickens, and several dogs.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_17_photos",
        topic="detail",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Why did Emma take many photos at the farm?",
        options=[
            "because her aunt asked her to",
            "because she loves animals",
            "because she had never visited a farm",
            "because she wanted to enter a competition",
        ],
        correct_answer="because she loves animals",
        accepted_answers=["she loves animals", "I love animals"],
        explanation="Emma took many photos because she loves animals.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_18_movie",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What did they do later that evening?",
        options=[
            "They swam in the river again.",
            "They rode bicycles to the farm.",
            "They ate dinner and watched a comedy movie.",
            "They made homemade bread.",
        ],
        correct_answer="They ate dinner and watched a comedy movie.",
        accepted_answers=[
            "ate dinner and watched a comedy",
            "watched a comedy movie",
        ],
        explanation="They were tired, so they ate dinner and watched a comedy movie together.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_19_bread",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What did Emma's aunt teach them on Sunday morning?",
        options=[
            "how to ride a bicycle",
            "how to swim in the river",
            "how to make homemade bread",
            "how to take photos of animals",
        ],
        correct_answer="how to make homemade bread",
        accepted_answers=["make homemade bread", "homemade bread"],
        explanation="On Sunday morning, Emma's aunt taught them how to make homemade bread.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_20_never_bread",
        topic="present_perfect",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Had Emma ever made homemade bread before this weekend?",
        options=[
            "Yes, she makes bread every Sunday.",
            "Yes, she had made bread once before.",
            "No, she had never made homemade bread before this weekend.",
            "She does not remember.",
        ],
        correct_answer="No, she had never made homemade bread before this weekend.",
        accepted_answers=["No", "never", "She has never made homemade bread."],
        explanation="Emma has never made homemade bread before this weekend.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_21_never_abroad",
        topic="present_perfect",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Has Emma ever traveled outside the country?",
        options=[
            "Yes, she has traveled abroad twice.",
            "Yes, she traveled last weekend.",
            "No, she has never traveled outside the country.",
            "She lives in another country.",
        ],
        correct_answer="No, she has never traveled outside the country.",
        accepted_answers=["No", "never", "She has never traveled abroad."],
        explanation="Emma has visited many places in her country, but she has never traveled outside the country.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_emma_weekend_22_parents",
        topic="present_perfect",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="How many times have Emma's parents traveled abroad?",
        options=["never", "once", "twice", "many times"],
        correct_answer="twice",
        accepted_answers=["two times", "two", "They have traveled abroad twice."],
        explanation="Emma's parents have traveled abroad twice.",
        audio_url=EMMA_WEEKEND_AUDIO_URL,
        clip_key=EMMA_WEEKEND_CLIP_KEY,
        clip_title=EMMA_WEEKEND_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_01_age",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="How old is Marcus?",
        options=["seventeen", "eighteen", "nineteen", "twenty"],
        correct_answer="nineteen",
        accepted_answers=["19", "nineteen years old", "He is nineteen."],
        explanation="Marcus says: 'I'm nineteen years old.'",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_02_study",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What does Marcus study?",
        options=["medicine", "computer science", "English literature", "business"],
        correct_answer="computer science",
        accepted_answers=["Computer Science", "He studies computer science."],
        explanation="Marcus studies computer science at a university in his city.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_03_interests",
        topic="detail",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What is one of Marcus's biggest interests?",
        options=["sports", "cooking", "technology", "music"],
        correct_answer="technology",
        accepted_answers=["Technology is one of his biggest interests."],
        explanation="Marcus says technology is one of his biggest interests, but English is also very important to him.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_04_wake_up",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What time does Marcus usually wake up?",
        options=[
            "at six thirty",
            "at seven in the morning",
            "at eight o'clock",
            "at nine o'clock",
        ],
        correct_answer="at seven in the morning",
        accepted_answers=["seven", "7:00", "at 7", "at seven"],
        explanation="Marcus usually wakes up at seven in the morning.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_05_phone",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What does Marcus do after he wakes up?",
        options=[
            "He checks his phone in bed.",
            "He has breakfast and takes a bus to the university.",
            "He goes to the library.",
            "He studies English online.",
        ],
        correct_answer="He has breakfast and takes a bus to the university.",
        accepted_answers=["have breakfast and take a bus", "breakfast and a bus"],
        explanation="He usually wakes up at seven, has breakfast, and takes a bus to the university.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_06_bus",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="How does Marcus go to the university?",
        options=[
            "He walks.",
            "He takes a bus.",
            "His parents drive him.",
            "He rides a bicycle.",
        ],
        correct_answer="He takes a bus.",
        accepted_answers=["by bus", "He takes a bus", "the bus"],
        explanation="After breakfast, Marcus takes a bus to the university.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_07_trip",
        topic="detail",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="How long does the trip to the university normally take?",
        options=[
            "about ten minutes",
            "about twenty minutes",
            "about forty minutes",
            "about one hour",
        ],
        correct_answer="about forty minutes",
        accepted_answers=["40 minutes", "forty minutes", "about 40 minutes"],
        explanation="The trip normally takes about forty minutes.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_08_classes",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What does Marcus often do after his classes?",
        options=[
            "He goes to a shopping mall.",
            "He goes to the library.",
            "He plays volleyball.",
            "He visits tourists.",
        ],
        correct_answer="He goes to the library.",
        accepted_answers=["go to the library", "He often goes to the library."],
        explanation="After his classes, he often goes to the library to study.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_09_library",
        topic="detail",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What does Marcus do in the library?",
        options=[
            "He watches movies in English.",
            "He studies, completes assignments, or works on programming projects.",
            "He talks to tourists.",
            "He takes the bus to the museum.",
        ],
        correct_answer="He studies, completes assignments, or works on programming projects.",
        accepted_answers=["study, complete assignments, or work on programming projects"],
        explanation="He goes to the library to study, complete assignments, or work on programming projects.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_10_evenings",
        topic="present_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="How often does Marcus study English online?",
        options=[
            "every morning",
            "once a month",
            "three evenings a week",
            "only on weekends",
        ],
        correct_answer="three evenings a week",
        accepted_answers=["3 evenings a week", "three times a week in the evening"],
        explanation="Three evenings a week, Marcus studies English online.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_11_started",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="When did Marcus start studying English seriously?",
        options=[
            "two months ago",
            "last weekend",
            "about three years ago",
            "when he was a child",
        ],
        correct_answer="about three years ago",
        accepted_answers=["three years ago", "about 3 years ago"],
        explanation="He started studying English seriously about three years ago.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_12_listening",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What was a big problem for Marcus at first?",
        options=["grammar", "listening", "programming", "reading"],
        correct_answer="listening",
        accepted_answers=["listening was a big problem", "listening comprehension"],
        explanation="At first, grammar was not very difficult for him, but listening was a big problem.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_13_mall",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Where was Marcus two months ago when something important happened?",
        options=[
            "at the university library",
            "on the bus",
            "at a shopping mall with two friends",
            "in an English-speaking country",
        ],
        correct_answer="at a shopping mall with two friends",
        accepted_answers=["at a shopping mall", "in a mall"],
        explanation="Two months ago he was at a shopping mall with two friends.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_14_why_speak",
        topic="detail",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Why did Marcus's friends ask him to talk to the tourist?",
        options=[
            "because Marcus had a map",
            "because Marcus was the only person in the group who could speak English",
            "because Marcus worked at the museum",
            "because Marcus was not nervous",
        ],
        correct_answer="because Marcus was the only person in the group who could speak English",
        accepted_answers=["he was the only person who could speak English"],
        explanation="His friends asked him to talk to the tourist because he was the only person in the group who could speak English.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_15_museum",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What was the tourist trying to find?",
        options=["a university", "a bus station", "a museum", "a shopping mall"],
        correct_answer="a museum",
        accepted_answers=["the museum", "He was trying to find a museum."],
        explanation="The tourist said that he was trying to find a museum.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_16_talk",
        topic="detail",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="How long did Marcus and the tourist talk?",
        options=[
            "less than one minute",
            "almost ten minutes",
            "about forty minutes",
            "almost three hours",
        ],
        correct_answer="almost ten minutes",
        accepted_answers=["almost 10 minutes", "ten minutes"],
        explanation="They talked for almost ten minutes.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_17_surprised",
        topic="past_simple",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Why was Marcus surprised after talking to the tourist?",
        options=[
            "The tourist spoke Spanish.",
            "The tourist told him that his English was very good.",
            "The tourist already knew where the museum was.",
            "His friends helped him speak.",
        ],
        correct_answer="The tourist told him that his English was very good.",
        accepted_answers=["the tourist said his English was very good"],
        explanation="The tourist thanked him and told him that his English was very good.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_18_visitors",
        topic="present_perfect",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="How many other foreign visitors has Marcus spoken English with since that experience?",
        options=["none", "one", "three", "many"],
        correct_answer="three",
        accepted_answers=["3", "three other foreign visitors"],
        explanation="He has spoken English with three other foreign visitors.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_19_movies",
        topic="present_perfect",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What has Marcus watched in English?",
        options=[
            "two complete movies",
            "one short video",
            "three podcasts",
            "a museum tour",
        ],
        correct_answer="two complete movies",
        accepted_answers=["two movies", "2 complete movies"],
        explanation="He has also watched two complete movies in English.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_20_never_english_country",
        topic="present_perfect",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Has Marcus ever visited an English-speaking country?",
        options=[
            "Yes, he has been to the United States.",
            "Yes, he has visited Canada.",
            "No, he has never visited an English-speaking country.",
            "He lives in the United Kingdom.",
        ],
        correct_answer="No, he has never visited an English-speaking country.",
        accepted_answers=["No", "never"],
        explanation="He has studied English for about three years, but he has never visited an English-speaking country.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_21_peru",
        topic="present_perfect",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="Where has Marcus traveled with his family?",
        options=["Canada", "Australia", "Peru", "the United Kingdom"],
        correct_answer="Peru",
        accepted_answers=["to Peru", "He has traveled to Peru."],
        explanation="He has traveled to Peru with his family, but they spoke Spanish there.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
    ListeningQuestionSeed(
        stable_key="listening_marcus_english_22_communication",
        topic="present_perfect",
        question_type="multiple_choice",
        instruction="Listen and choose the correct answer.",
        question="What is one of Marcus's goals?",
        options=[
            "to stop studying English",
            "to travel abroad and use English every day",
            "to work in a museum",
            "to live in Peru",
        ],
        correct_answer="to travel abroad and use English every day",
        accepted_answers=[
            "travel abroad",
            "use English every day",
            "work for an international technology company",
        ],
        explanation="One of his goals is to travel abroad and use English every day. He also wants to work for an international technology company.",
        audio_url=MARCUS_ENGLISH_AUDIO_URL,
        clip_key=MARCUS_ENGLISH_CLIP_KEY,
        clip_title=MARCUS_ENGLISH_CLIP_TITLE,
    ),
]
