"""Initial question bank for the Past Simple Exam."""

from dataclasses import dataclass


@dataclass(frozen=True)
class PastSimpleQuestionSeed:
    stable_key: str
    topic: str
    question_type: str
    instruction: str
    question: str
    options: list[str] | None
    correct_answer: str
    accepted_answers: list[str]
    explanation: str
    points: int = 1
    active: bool = True


PAST_SIMPLE_QUESTIONS: list[PastSimpleQuestionSeed] = [
    # Interrogative structure
    PastSimpleQuestionSeed(
        stable_key="past_simple_interrogative_structure_01",
        topic="interrogative_structure",
        question_type="multiple_choice",
        instruction="Choose the correct question.",
        question="Which sentence has the correct Past Simple interrogative structure?",
        options=[
            "You did study English yesterday?",
            "Did you study English yesterday?",
            "Did study you English yesterday?",
            "You studied did English yesterday?",
        ],
        correct_answer="Did you study English yesterday?",
        accepted_answers=[],
        explanation="Past Simple questions use: Did + subject + base verb.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_interrogative_structure_02",
        topic="interrogative_structure",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="she / did / watch / the movie",
        options=None,
        correct_answer="Did she watch the movie?",
        accepted_answers=[],
        explanation="Place did before the subject and use the base verb watch.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_interrogative_structure_03",
        topic="interrogative_structure",
        question_type="transform_question",
        instruction="Change the sentence into a Past Simple question.",
        question="They cleaned the classroom after school.",
        options=None,
        correct_answer="Did they clean the classroom after school?",
        accepted_answers=[],
        explanation="Use did before the subject and change cleaned to the base form clean.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_interrogative_structure_04",
        topic="interrogative_structure",
        question_type="error_correction",
        instruction="Correct the question.",
        question="Played Maria tennis on Saturday?",
        options=None,
        correct_answer="Did Maria play tennis on Saturday?",
        accepted_answers=[],
        explanation="A Past Simple question needs did before the subject and the base verb play.",
    ),
    # Use of did
    PastSimpleQuestionSeed(
        stable_key="past_simple_use_of_did_01",
        topic="use_of_did",
        question_type="multiple_choice",
        instruction="Choose the correct word.",
        question="___ you visit your grandmother yesterday?",
        options=["Do", "Did", "Were", "Was"],
        correct_answer="Did",
        accepted_answers=[],
        explanation="Use did to form a Past Simple question with an action verb.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_use_of_did_02",
        topic="use_of_did",
        question_type="multiple_choice",
        instruction="Choose the correct sentence.",
        question="Which question uses did correctly?",
        options=[
            "Did they played soccer?",
            "Did they play soccer?",
            "Did they playing soccer?",
            "Did played they soccer?",
        ],
        correct_answer="Did they play soccer?",
        accepted_answers=[],
        explanation="After did, the verb must be in its base form.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_use_of_did_03",
        topic="use_of_did",
        question_type="fill_blank",
        instruction="Complete the question with one word.",
        question="What ___ your brother cook for dinner last night?",
        options=None,
        correct_answer="did",
        accepted_answers=[],
        explanation="Did is the Past Simple auxiliary used before the subject your brother.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_use_of_did_04",
        topic="use_of_did",
        question_type="error_correction",
        instruction="Correct the question.",
        question="Did Laura brought her notebook?",
        options=None,
        correct_answer="Did Laura bring her notebook?",
        accepted_answers=[],
        explanation="After did, use the base form bring, not the past form brought.",
    ),
    # Regular and irregular verbs
    PastSimpleQuestionSeed(
        stable_key="past_simple_regular_irregular_verbs_01",
        topic="regular_irregular_verbs",
        question_type="multiple_choice",
        instruction="Choose the correct verb.",
        question="Did she ___ to school yesterday?",
        options=["went", "goes", "go", "going"],
        correct_answer="go",
        accepted_answers=[],
        explanation="The irregular verb go returns to its base form after did.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_regular_irregular_verbs_02",
        topic="regular_irregular_verbs",
        question_type="multiple_choice",
        instruction="Choose the correct verb.",
        question="Did they ___ television last night?",
        options=["watched", "watch", "watches", "watching"],
        correct_answer="watch",
        accepted_answers=[],
        explanation="Both regular and irregular verbs return to the base form after did.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_regular_irregular_verbs_03",
        topic="regular_irregular_verbs",
        question_type="fill_blank",
        instruction="Complete the sentence with the Past Simple form of the verb in parentheses.",
        question="Nora ___ a letter to her cousin yesterday. (write)",
        options=None,
        correct_answer="wrote",
        accepted_answers=[],
        explanation="Wrote is the irregular Past Simple form of write.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_regular_irregular_verbs_04",
        topic="regular_irregular_verbs",
        question_type="fill_blank",
        instruction="Complete the sentence with the Past Simple form of the verb in parentheses.",
        question="The students ___ for the test last weekend. (study)",
        options=None,
        correct_answer="studied",
        accepted_answers=[],
        explanation="Study is regular, but a consonant replaces the final y before -ed: studied.",
    ),
    # Short answers
    PastSimpleQuestionSeed(
        stable_key="past_simple_short_answers_01",
        topic="short_answers",
        question_type="multiple_choice",
        instruction="Choose the correct short answer.",
        question="Did Carlos study for the exam?",
        options=["Yes, he did.", "Yes, he studied.", "Yes, he does.", "Yes, he was."],
        correct_answer="Yes, he did.",
        accepted_answers=[],
        explanation="An affirmative short answer uses yes + subject pronoun + did.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_short_answers_02",
        topic="short_answers",
        question_type="multiple_choice",
        instruction="Choose the correct short answer.",
        question="Did Anna go to the party?",
        options=["No, she doesn't.", "No, she wasn't.", "No, she didn't.", "No, she not."],
        correct_answer="No, she didn't.",
        accepted_answers=[],
        explanation="A negative Past Simple short answer uses didn't.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_short_answers_03",
        topic="short_answers",
        question_type="fill_blank",
        instruction="Write a negative short answer.",
        question="Did the children finish their homework?",
        options=None,
        correct_answer="No, they didn't.",
        accepted_answers=["No, they did not."],
        explanation="Use they for the children and didn't (or did not) in a negative short answer.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_short_answers_04",
        topic="short_answers",
        question_type="error_correction",
        instruction="Correct the short answer.",
        question="Did Mark call you? Yes, Mark did.",
        options=None,
        correct_answer="Yes, he did.",
        accepted_answers=[],
        explanation="Short answers normally repeat the subject as a pronoun: Mark becomes he.",
    ),
    # Was and were
    PastSimpleQuestionSeed(
        stable_key="past_simple_was_were_01",
        topic="was_were",
        question_type="multiple_choice",
        instruction="Choose the correct word.",
        question="___ she at school yesterday?",
        options=["Did", "Were", "Was", "Does"],
        correct_answer="Was",
        accepted_answers=[],
        explanation="Use was with I, he, she, and it.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_was_were_02",
        topic="was_were",
        question_type="multiple_choice",
        instruction="Choose the correct word.",
        question="___ they tired after the game?",
        options=["Was", "Were", "Did", "Are"],
        correct_answer="Were",
        accepted_answers=[],
        explanation="Use were with you, we, and they.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_was_were_03",
        topic="was_were",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="your parents / were / at home / last night",
        options=None,
        correct_answer="Were your parents at home last night?",
        accepted_answers=[],
        explanation="Questions with were place were before the plural subject.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_was_were_04",
        topic="was_were",
        question_type="error_correction",
        instruction="Correct the question.",
        question="Were the concert exciting?",
        options=None,
        correct_answer="Was the concert exciting?",
        accepted_answers=[],
        explanation="Concert is singular, so the correct Past Simple form of be is was.",
    ),
    # General question words
    PastSimpleQuestionSeed(
        stable_key="past_simple_question_words_01",
        topic="question_words",
        question_type="multiple_choice",
        instruction="Choose the correct structure.",
        question="Which is the standard structure for a Past Simple question with a question word?",
        options=[
            "Question Word + subject + did + verb",
            "Did + Question Word + subject + verb",
            "Question Word + did + subject + base verb",
            "Subject + Question Word + did + verb",
        ],
        correct_answer="Question Word + did + subject + base verb",
        accepted_answers=[],
        explanation="The standard structure is question word + did + subject + base verb.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_question_words_02",
        topic="question_words",
        question_type="multiple_choice",
        instruction="Choose the correct question.",
        question="Which question has the correct word order and verb form?",
        options=[
            "Where you did go?",
            "Where did you went?",
            "Where did you go?",
            "Did where you go?",
        ],
        correct_answer="Where did you go?",
        accepted_answers=[],
        explanation="Put the question word first, then did, the subject, and the base verb.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_question_words_03",
        topic="question_words",
        question_type="fill_blank",
        instruction="Choose the most suitable question word and write it in the blank.",
        question="___ did the meeting start? At nine o'clock.",
        options=None,
        correct_answer="When",
        accepted_answers=[],
        explanation="When asks about time, and the answer gives a specific time.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_question_words_04",
        topic="question_words",
        question_type="error_correction",
        instruction="Correct the question.",
        question="Why did the baby cried?",
        options=None,
        correct_answer="Why did the baby cry?",
        accepted_answers=[],
        explanation="After did, use the base form cry.",
    ),
    # What
    PastSimpleQuestionSeed(
        stable_key="past_simple_what_01",
        topic="what",
        question_type="multiple_choice",
        instruction="Choose the correct question word.",
        question="___ did you eat for breakfast?",
        options=["Where", "What", "When", "Who"],
        correct_answer="What",
        accepted_answers=[],
        explanation="What asks about a thing, action, or general information.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_what_02",
        topic="what",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="what / she / did / study / yesterday",
        options=None,
        correct_answer="What did she study yesterday?",
        accepted_answers=[],
        explanation="Use what + did + subject + base verb.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_what_03",
        topic="what",
        question_type="transform_question",
        instruction=(
            "Write a question about the underlined information represented by CAPITAL LETTERS."
        ),
        question="Daniel bought A NEW BACKPACK yesterday.",
        options=None,
        correct_answer="What did Daniel buy yesterday?",
        accepted_answers=[],
        explanation="Use what to ask about the thing Daniel bought, and use buy after did.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_what_04",
        topic="what",
        question_type="multiple_choice",
        instruction="Choose the question that matches the answer.",
        question="Answer: We watched a documentary after dinner.",
        options=[
            "What did you watch after dinner?",
            "Where did you watch after dinner?",
            "When did you watch a documentary?",
            "Who did you watch after dinner?",
        ],
        correct_answer="What did you watch after dinner?",
        accepted_answers=[],
        explanation="What asks for the thing that the speakers watched.",
    ),
    # Where
    PastSimpleQuestionSeed(
        stable_key="past_simple_where_01",
        topic="where",
        question_type="multiple_choice",
        instruction="Choose the correct question word.",
        question="___ did they play soccer?",
        options=["Why", "When", "Where", "How"],
        correct_answer="Where",
        accepted_answers=[],
        explanation="Where asks about a place.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_where_02",
        topic="where",
        question_type="multiple_choice",
        instruction="Choose the correct question.",
        question="Which question correctly asks about a place?",
        options=[
            "Where did he buy the food?",
            "Where did he bought the food?",
            "Where he did buy the food?",
            "Did where he buy the food?",
        ],
        correct_answer="Where did he buy the food?",
        accepted_answers=[],
        explanation="Use where + did + subject + base verb.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_where_03",
        topic="where",
        question_type="transform_question",
        instruction="Write a question about the place shown in CAPITAL LETTERS.",
        question="Mia left her keys ON THE KITCHEN TABLE.",
        options=None,
        correct_answer="Where did Mia leave her keys?",
        accepted_answers=[],
        explanation="Where asks about the place, and leave is the base form used after did.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_where_04",
        topic="where",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="the bus / stop / where / did",
        options=None,
        correct_answer="Where did the bus stop?",
        accepted_answers=[],
        explanation="The correct order is where + did + subject + base verb.",
    ),
    # When
    PastSimpleQuestionSeed(
        stable_key="past_simple_when_01",
        topic="when",
        question_type="multiple_choice",
        instruction="Choose the correct question word.",
        question="___ did she arrive home?",
        options=["When", "Who", "Why", "What"],
        correct_answer="When",
        accepted_answers=[],
        explanation="When asks about the time an action happened.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_when_02",
        topic="when",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="when / they / did / visit / their grandparents",
        options=None,
        correct_answer="When did they visit their grandparents?",
        accepted_answers=[],
        explanation="Use when + did + subject + base verb.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_when_03",
        topic="when",
        question_type="transform_question",
        instruction="Write a question about the time shown in CAPITAL LETTERS.",
        question="The movie ended AT 10:30 P.M.",
        options=None,
        correct_answer="When did the movie end?",
        accepted_answers=["What time did the movie end?"],
        explanation="When asks about time; what time is also correct when asking for a clock time.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_when_04",
        topic="when",
        question_type="multiple_choice",
        instruction="Choose the question that matches the answer.",
        question="Answer: Leo started his new job last Monday.",
        options=[
            "When did Leo start his new job?",
            "Where did Leo start his new job?",
            "Why did Leo start his new job?",
            "Who did Leo start his new job?",
        ],
        correct_answer="When did Leo start his new job?",
        accepted_answers=[],
        explanation="When asks for the time of Leo's action.",
    ),
    # Why
    PastSimpleQuestionSeed(
        stable_key="past_simple_why_01",
        topic="why",
        question_type="multiple_choice",
        instruction="Choose the correct question word.",
        question="___ did he leave early?",
        options=["What", "Where", "Why", "Who"],
        correct_answer="Why",
        accepted_answers=[],
        explanation="Why asks for the reason an action happened.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_why_02",
        topic="why",
        question_type="multiple_choice",
        instruction="Choose the best answer.",
        question="Why did she stay at home?",
        options=["At home.", "Because she was tired.", "Yesterday.", "Her sister."],
        correct_answer="Because she was tired.",
        accepted_answers=[],
        explanation="A why question asks for a reason, commonly introduced by because.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_why_03",
        topic="why",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="cancel / Tom / why / the picnic / did",
        options=None,
        correct_answer="Why did Tom cancel the picnic?",
        accepted_answers=[],
        explanation="Use why + did + subject + base verb to ask for a reason.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_why_04",
        topic="why",
        question_type="error_correction",
        instruction="Correct the question.",
        question="Why Emma did close the window?",
        options=None,
        correct_answer="Why did Emma close the window?",
        accepted_answers=[],
        explanation="Did must come before the subject in this why question.",
    ),
    # Who
    PastSimpleQuestionSeed(
        stable_key="past_simple_who_01",
        topic="who",
        question_type="multiple_choice",
        instruction="Choose the correct question word.",
        question="___ did you call last night?",
        options=["Who", "When", "How", "Where"],
        correct_answer="Who",
        accepted_answers=[],
        explanation="Who asks about the person who received the call.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_who_02",
        topic="who",
        question_type="multiple_choice",
        instruction="Choose the correct question.",
        question="Which question correctly asks about the person she visited?",
        options=[
            "Who did she visit?",
            "Who did she visited?",
            "Who she did visit?",
            "Did who she visit?",
        ],
        correct_answer="Who did she visit?",
        accepted_answers=[],
        explanation="When who is the object, use who + did + subject + base verb.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_who_03",
        topic="who",
        question_type="multiple_choice",
        instruction="Choose the correct subject question.",
        question="Which question asks for the person who performed the action?",
        options=[
            "Who called you?",
            "Who did call you?",
            "Who did you called?",
            "Did who call you?",
        ],
        correct_answer="Who called you?",
        accepted_answers=[],
        explanation="When who is the subject, use the Past Simple verb directly without did.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_who_04",
        topic="who",
        question_type="transform_question",
        instruction="Write a subject question about the person shown in CAPITAL LETTERS.",
        question="MR. BROWN taught the class yesterday.",
        options=None,
        correct_answer="Who taught the class yesterday?",
        accepted_answers=[],
        explanation=(
            "Who replaces the subject, so the irregular past verb taught stays and did is not used."
        ),
    ),
    # How
    PastSimpleQuestionSeed(
        stable_key="past_simple_how_01",
        topic="how",
        question_type="multiple_choice",
        instruction="Choose the correct question word.",
        question="___ did you travel to school?",
        options=["What", "Why", "How", "Who"],
        correct_answer="How",
        accepted_answers=[],
        explanation="How asks about the way or method used to do something.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_how_02",
        topic="how",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="how / she / did / learn / English",
        options=None,
        correct_answer="How did she learn English?",
        accepted_answers=[],
        explanation="Use how + did + subject + base verb.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_how_03",
        topic="how",
        question_type="multiple_choice",
        instruction="Choose the question that matches the answer.",
        question="Answer: They traveled to the island by boat.",
        options=[
            "How did they travel to the island?",
            "When did they travel to the island?",
            "Why did they travel to the island?",
            "Who did they travel to the island?",
        ],
        correct_answer="How did they travel to the island?",
        accepted_answers=[],
        explanation="How asks about the method of travel.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_how_04",
        topic="how",
        question_type="error_correction",
        instruction="Correct the question.",
        question="How did Sofia solved the problem?",
        options=None,
        correct_answer="How did Sofia solve the problem?",
        accepted_answers=[],
        explanation="After did, use the base form solve.",
    ),
    # --- Extra bank (bring each topic to at least 8; four topics to 9) ---
    # Interrogative structure (+5 → 9)
    PastSimpleQuestionSeed(
        stable_key="past_simple_interrogative_structure_05",
        topic="interrogative_structure",
        question_type="multiple_choice",
        instruction="Choose the correct question.",
        question="Which sentence has the correct Past Simple interrogative structure?",
        options=[
            "Did your friends enjoy the concert?",
            "Your friends did enjoy the concert?",
            "Did enjoy your friends the concert?",
            "Enjoyed your friends the concert?",
        ],
        correct_answer="Did your friends enjoy the concert?",
        accepted_answers=[],
        explanation="Past Simple questions use: Did + subject + base verb.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_interrogative_structure_06",
        topic="interrogative_structure",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="finish / they / did / their project",
        options=None,
        correct_answer="Did they finish their project?",
        accepted_answers=[],
        explanation="Place did before the subject and use the base verb finish.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_interrogative_structure_07",
        topic="interrogative_structure",
        question_type="transform_question",
        instruction="Change the sentence into a Past Simple question.",
        question="Sam opened the window this morning.",
        options=None,
        correct_answer="Did Sam open the window this morning?",
        accepted_answers=[],
        explanation="Use did before the subject and change opened to the base form open.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_interrogative_structure_08",
        topic="interrogative_structure",
        question_type="fill_blank",
        instruction="Complete the question with the missing auxiliary.",
        question="___ the teacher explain the homework yesterday?",
        options=None,
        correct_answer="Did",
        accepted_answers=["did"],
        explanation="Did is the Past Simple auxiliary placed before the subject.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_interrogative_structure_09",
        topic="interrogative_structure",
        question_type="error_correction",
        instruction="Correct the question.",
        question="Did your sister helped you with the bags?",
        options=None,
        correct_answer="Did your sister help you with the bags?",
        accepted_answers=[],
        explanation="After did, use the base form help, not the past form helped.",
    ),
    # Use of did (+5 → 9)
    PastSimpleQuestionSeed(
        stable_key="past_simple_use_of_did_05",
        topic="use_of_did",
        question_type="multiple_choice",
        instruction="Choose the correct word.",
        question="___ your classmates finish the worksheet?",
        options=["Do", "Does", "Did", "Were"],
        correct_answer="Did",
        accepted_answers=[],
        explanation="Use did to ask about a finished Past Simple action.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_use_of_did_06",
        topic="use_of_did",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="the email / send / did / you",
        options=None,
        correct_answer="Did you send the email?",
        accepted_answers=[],
        explanation="Use did + subject + base verb, then the object.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_use_of_did_07",
        topic="use_of_did",
        question_type="fill_blank",
        instruction="Complete the question with one word.",
        question="Where ___ your parents park the car?",
        options=None,
        correct_answer="did",
        accepted_answers=["Did"],
        explanation="Did comes after the question word and before the subject.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_use_of_did_08",
        topic="use_of_did",
        question_type="multiple_choice",
        instruction="Choose the correct sentence.",
        question="Which question uses did correctly?",
        options=[
            "Did she wrote a story?",
            "Did she write a story?",
            "Did she writing a story?",
            "Did wrote she a story?",
        ],
        correct_answer="Did she write a story?",
        accepted_answers=[],
        explanation="After did, the verb must be in its base form write.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_use_of_did_09",
        topic="use_of_did",
        question_type="error_correction",
        instruction="Correct the question.",
        question="Did the kids ate all the cookies?",
        options=None,
        correct_answer="Did the kids eat all the cookies?",
        accepted_answers=[],
        explanation="After did, use the base form eat, not ate.",
    ),
    # Regular and irregular verbs (+4 → 8)
    PastSimpleQuestionSeed(
        stable_key="past_simple_regular_irregular_verbs_05",
        topic="regular_irregular_verbs",
        question_type="multiple_choice",
        instruction="Choose the correct verb.",
        question="Did he ___ the door before leaving?",
        options=["closed", "close", "closes", "closing"],
        correct_answer="close",
        accepted_answers=[],
        explanation="After did, use the base form close, even for regular verbs.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_regular_irregular_verbs_06",
        topic="regular_irregular_verbs",
        question_type="fill_blank",
        instruction="Complete the sentence with the Past Simple form of the verb in parentheses.",
        question="We ___ a great movie last Friday. (see)",
        options=None,
        correct_answer="saw",
        accepted_answers=[],
        explanation="Saw is the irregular Past Simple form of see.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_regular_irregular_verbs_07",
        topic="regular_irregular_verbs",
        question_type="fill_blank",
        instruction="Complete the sentence with the Past Simple form of the verb in parentheses.",
        question="Lina ___ the invitations carefully. (check)",
        options=None,
        correct_answer="checked",
        accepted_answers=[],
        explanation="Check is regular, so add -ed: checked.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_regular_irregular_verbs_08",
        topic="regular_irregular_verbs",
        question_type="error_correction",
        instruction="Correct the question.",
        question="Did they took the train to Madrid?",
        options=None,
        correct_answer="Did they take the train to Madrid?",
        accepted_answers=[],
        explanation="After did, the irregular verb take returns to its base form.",
    ),
    # Short answers (+5 → 9)
    PastSimpleQuestionSeed(
        stable_key="past_simple_short_answers_05",
        topic="short_answers",
        question_type="multiple_choice",
        instruction="Choose the correct short answer.",
        question="Did you like the museum?",
        options=["Yes, I did.", "Yes, I liked.", "Yes, I do.", "Yes, I was."],
        correct_answer="Yes, I did.",
        accepted_answers=[],
        explanation="An affirmative short answer uses yes + subject pronoun + did.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_short_answers_06",
        topic="short_answers",
        question_type="fill_blank",
        instruction="Write an affirmative short answer.",
        question="Did Paula pass the test?",
        options=None,
        correct_answer="Yes, she did.",
        accepted_answers=["Yes she did.", "Yes, she did"],
        explanation="Use she for Paula and did in an affirmative short answer.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_short_answers_07",
        topic="short_answers",
        question_type="multiple_choice",
        instruction="Choose the correct short answer.",
        question="Did we forget the tickets?",
        options=["No, we didn't.", "No, we don't.", "No, we weren't.", "No, we not."],
        correct_answer="No, we didn't.",
        accepted_answers=[],
        explanation="A negative Past Simple short answer uses didn't.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_short_answers_08",
        topic="short_answers",
        question_type="error_correction",
        instruction="Correct the short answer.",
        question="Did the girls practice piano? No, the girls didn't.",
        options=None,
        correct_answer="No, they didn't.",
        accepted_answers=["No, they did not."],
        explanation="Short answers normally use a pronoun: the girls becomes they.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_short_answers_09",
        topic="short_answers",
        question_type="transform_question",
        instruction="Write a negative short answer to the question.",
        question="Did your uncle drive to work?",
        options=None,
        correct_answer="No, he didn't.",
        accepted_answers=["No, he did not."],
        explanation="Use he for your uncle and didn't (or did not) in a negative short answer.",
    ),
    # Was and were (+5 → 9)
    PastSimpleQuestionSeed(
        stable_key="past_simple_was_were_05",
        topic="was_were",
        question_type="multiple_choice",
        instruction="Choose the correct word.",
        question="___ your brother busy last weekend?",
        options=["Were", "Was", "Did", "Are"],
        correct_answer="Was",
        accepted_answers=[],
        explanation="Your brother is singular, so use was.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_was_were_06",
        topic="was_were",
        question_type="fill_blank",
        instruction="Complete the question with was or were.",
        question="___ you at the library after class?",
        options=None,
        correct_answer="Were",
        accepted_answers=["were"],
        explanation="Use were with you.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_was_were_07",
        topic="was_were",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="hungry / was / after practice / he",
        options=None,
        correct_answer="Was he hungry after practice?",
        accepted_answers=[],
        explanation="Questions with was place was before the singular subject.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_was_were_08",
        topic="was_were",
        question_type="error_correction",
        instruction="Correct the question.",
        question="Was your cousins late for the meeting?",
        options=None,
        correct_answer="Were your cousins late for the meeting?",
        accepted_answers=[],
        explanation="Cousins is plural, so use were.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_was_were_09",
        topic="was_were",
        question_type="multiple_choice",
        instruction="Choose the correct sentence.",
        question="Which question is correct?",
        options=[
            "Was the stores open yesterday?",
            "Were the store open yesterday?",
            "Were the stores open yesterday?",
            "Did the stores were open yesterday?",
        ],
        correct_answer="Were the stores open yesterday?",
        accepted_answers=[],
        explanation="Stores is plural, so the Past Simple of be is were.",
    ),
    # Question words (+4 → 8)
    PastSimpleQuestionSeed(
        stable_key="past_simple_question_words_05",
        topic="question_words",
        question_type="multiple_choice",
        instruction="Choose the correct question.",
        question="Which question has the correct word order?",
        options=[
            "What time did the train arrive?",
            "What time the train did arrive?",
            "What time did the train arrived?",
            "Did what time the train arrive?",
        ],
        correct_answer="What time did the train arrive?",
        accepted_answers=[],
        explanation="Use question word(s) + did + subject + base verb.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_question_words_06",
        topic="question_words",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="buy / why / did / those shoes / you",
        options=None,
        correct_answer="Why did you buy those shoes?",
        accepted_answers=[],
        explanation="Put the question word first, then did, the subject, and the base verb.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_question_words_07",
        topic="question_words",
        question_type="fill_blank",
        instruction="Choose the most suitable question word and write it in the blank.",
        question="___ did they go after dinner? To the park.",
        options=None,
        correct_answer="Where",
        accepted_answers=["where"],
        explanation="Where asks about a place, and the answer names a place.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_question_words_08",
        topic="question_words",
        question_type="error_correction",
        instruction="Correct the question.",
        question="How you did fix the computer?",
        options=None,
        correct_answer="How did you fix the computer?",
        accepted_answers=[],
        explanation="Did must come before the subject in a Past Simple question.",
    ),
    # What (+4 → 8)
    PastSimpleQuestionSeed(
        stable_key="past_simple_what_05",
        topic="what",
        question_type="fill_blank",
        instruction="Complete the question with the correct question word.",
        question="___ did you find in the drawer?",
        options=None,
        correct_answer="What",
        accepted_answers=["what"],
        explanation="What asks about a thing or object.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_what_06",
        topic="what",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="what / did / for lunch / cook / they",
        options=None,
        correct_answer="What did they cook for lunch?",
        accepted_answers=[],
        explanation="Use what + did + subject + base verb.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_what_07",
        topic="what",
        question_type="transform_question",
        instruction=(
            "Write a question about the underlined information represented by CAPITAL LETTERS."
        ),
        question="Clara ordered PIZZA for dinner.",
        options=None,
        correct_answer="What did Clara order for dinner?",
        accepted_answers=[],
        explanation="Use what to ask about the thing Clara ordered, and use order after did.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_what_08",
        topic="what",
        question_type="error_correction",
        instruction="Correct the question.",
        question="What did you bought at the store?",
        options=None,
        correct_answer="What did you buy at the store?",
        accepted_answers=[],
        explanation="After did, use the base form buy.",
    ),
    # Where (+4 → 8)
    PastSimpleQuestionSeed(
        stable_key="past_simple_where_05",
        topic="where",
        question_type="multiple_choice",
        instruction="Choose the question that matches the answer.",
        question="Answer: They parked near the stadium.",
        options=[
            "Where did they park?",
            "When did they park?",
            "Why did they park?",
            "What did they park?",
        ],
        correct_answer="Where did they park?",
        accepted_answers=[],
        explanation="Where asks for the place mentioned in the answer.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_where_06",
        topic="where",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="put / where / did / the suitcase / Emma",
        options=None,
        correct_answer="Where did Emma put the suitcase?",
        accepted_answers=[],
        explanation="The correct order is where + did + subject + base verb + object.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_where_07",
        topic="where",
        question_type="transform_question",
        instruction="Write a question about the place shown in CAPITAL LETTERS.",
        question="The kids hid the gifts UNDER THE BED.",
        options=None,
        correct_answer="Where did the kids hide the gifts?",
        accepted_answers=[],
        explanation="Where asks about the place, and hide is the base form used after did.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_where_08",
        topic="where",
        question_type="fill_blank",
        instruction="Complete the question with the correct question word.",
        question="___ did Alex wait for the taxi?",
        options=None,
        correct_answer="Where",
        accepted_answers=["where"],
        explanation="Where asks about a place.",
    ),
    # When (+4 → 8)
    PastSimpleQuestionSeed(
        stable_key="past_simple_when_05",
        topic="when",
        question_type="fill_blank",
        instruction="Complete the question with the correct question word.",
        question="___ did the class begin?",
        options=None,
        correct_answer="When",
        accepted_answers=["when"],
        explanation="When asks about time.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_when_06",
        topic="when",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="when / did / leave / the airport / you",
        options=None,
        correct_answer="When did you leave the airport?",
        accepted_answers=[],
        explanation="Use when + did + subject + base verb.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_when_07",
        topic="when",
        question_type="transform_question",
        instruction="Write a question about the time shown in CAPITAL LETTERS.",
        question="Julia called her mom AFTER LUNCH.",
        options=None,
        correct_answer="When did Julia call her mom?",
        accepted_answers=[],
        explanation="When asks about the time of the action, and call is the base form after did.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_when_08",
        topic="when",
        question_type="error_correction",
        instruction="Correct the question.",
        question="When did the show started?",
        options=None,
        correct_answer="When did the show start?",
        accepted_answers=[],
        explanation="After did, use the base form start.",
    ),
    # Why (+4 → 8)
    PastSimpleQuestionSeed(
        stable_key="past_simple_why_05",
        topic="why",
        question_type="multiple_choice",
        instruction="Choose the question that matches the answer.",
        question="Answer: Because it started to rain.",
        options=[
            "Why did they go inside?",
            "Where did they go inside?",
            "When did they go inside?",
            "Who did they go inside?",
        ],
        correct_answer="Why did they go inside?",
        accepted_answers=[],
        explanation="Why asks for a reason, often answered with because.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_why_06",
        topic="why",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="leave / early / why / did / the guests",
        options=None,
        correct_answer="Why did the guests leave early?",
        accepted_answers=[],
        explanation="Use why + did + subject + base verb.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_why_07",
        topic="why",
        question_type="transform_question",
        instruction="Write a why question about the reason shown in CAPITAL LETTERS.",
        question="Ben stayed home BECAUSE HE FELT SICK.",
        options=None,
        correct_answer="Why did Ben stay home?",
        accepted_answers=["Why did Ben stay at home?"],
        explanation="Why asks for the reason; stay is the base form used after did.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_why_08",
        topic="why",
        question_type="fill_blank",
        instruction="Complete the question with the correct question word.",
        question="___ did Marta change her plans?",
        options=None,
        correct_answer="Why",
        accepted_answers=["why"],
        explanation="Why asks for a reason.",
    ),
    # Who (+4 → 8)
    PastSimpleQuestionSeed(
        stable_key="past_simple_who_05",
        topic="who",
        question_type="multiple_choice",
        instruction="Choose the question that matches the answer.",
        question="Answer: She invited her cousin.",
        options=[
            "Who did she invite?",
            "When did she invite?",
            "Where did she invite?",
            "How did she invite?",
        ],
        correct_answer="Who did she invite?",
        accepted_answers=[],
        explanation="Who asks about the person who received the action.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_who_06",
        topic="who",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="who / help / did / with the boxes / you",
        options=None,
        correct_answer="Who did you help with the boxes?",
        accepted_answers=[],
        explanation="When who is the object, use who + did + subject + base verb.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_who_07",
        topic="who",
        question_type="transform_question",
        instruction="Write a subject question about the person shown in CAPITAL LETTERS.",
        question="ANA fixed the broken laptop.",
        options=None,
        correct_answer="Who fixed the broken laptop?",
        accepted_answers=[],
        explanation="Who replaces the subject, so the past verb fixed stays and did is not used.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_who_08",
        topic="who",
        question_type="error_correction",
        instruction="Correct the question.",
        question="Who did open the door?",
        options=None,
        correct_answer="Who opened the door?",
        accepted_answers=[],
        explanation="When who is the subject, use the Past Simple verb directly without did.",
    ),
    # How (+4 → 8)
    PastSimpleQuestionSeed(
        stable_key="past_simple_how_05",
        topic="how",
        question_type="multiple_choice",
        instruction="Choose the correct question.",
        question="Which question correctly asks about the method?",
        options=[
            "How did they open the box?",
            "How did they opened the box?",
            "How they did open the box?",
            "Did how they open the box?",
        ],
        correct_answer="How did they open the box?",
        accepted_answers=[],
        explanation="Use how + did + subject + base verb.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_how_06",
        topic="how",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="how / get / did / to the station / he",
        options=None,
        correct_answer="How did he get to the station?",
        accepted_answers=[],
        explanation="Use how + did + subject + base verb.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_how_07",
        topic="how",
        question_type="fill_blank",
        instruction="Complete the question with the correct question word.",
        question="___ did you prepare for the presentation?",
        options=None,
        correct_answer="How",
        accepted_answers=["how"],
        explanation="How asks about the way or method used.",
    ),
    PastSimpleQuestionSeed(
        stable_key="past_simple_how_08",
        topic="how",
        question_type="transform_question",
        instruction="Write a question about the method shown in CAPITAL LETTERS.",
        question="Nina sent the files BY EMAIL.",
        options=None,
        correct_answer="How did Nina send the files?",
        accepted_answers=[],
        explanation="How asks about the method; send is the base form used after did.",
    ),
]
