"""Banco inicial de preguntas para Present Perfect Exam/Practice."""

from dataclasses import dataclass


@dataclass(frozen=True)
class PresentPerfectQuestionSeed:
    stable_key: str
    topic: str
    question_type: str
    instruction: str
    question: str
    options: list[str] | None
    correct_answer: str
    accepted_answers: list[str]
    explanation: str
    points: int = 1
    active: bool = True


PRESENT_PERFECT_QUESTIONS: list[PresentPerfectQuestionSeed] = [
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_affirmative_01",
        topic="affirmative",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="Which sentence is correct in the Present Perfect?",
        options=[
            "She has finished her homework.",
            "She have finished her homework.",
            "She finished her homework yesterday already.",
            "She has finish her homework.",
        ],
        correct_answer="She has finished her homework.",
        accepted_answers=[],
        explanation="Use has with she + past participle: has finished.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_affirmative_02",
        topic="affirmative",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="Choose the correct sentence.",
        options=[
            "They has visited Paris.",
            "They have visited Paris.",
            "They have visit Paris.",
            "They visited Paris just now already.",
        ],
        correct_answer="They have visited Paris.",
        accepted_answers=[],
        explanation="With they, use have + past participle.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_affirmative_03",
        topic="affirmative",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="Tom ___ to Mexico three times.",
        options=["has been", "have been", "was", "is being"],
        correct_answer="has been",
        accepted_answers=[],
        explanation="Tom is he → has been.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_affirmative_04",
        topic="affirmative",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="I ___ that movie before.",
        options=["have seen", "has seen", "saw", "seeing"],
        correct_answer="have seen",
        accepted_answers=[],
        explanation="With I, use have + past participle.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_affirmative_05",
        topic="affirmative",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="We ___ already ___ lunch.",
        options=["have / eaten", "has / eaten", "have / ate", "are / eaten"],
        correct_answer="have / eaten",
        accepted_answers=[],
        explanation="We + have + past participle eaten.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_affirmative_06",
        topic="affirmative",
        question_type="fill_blank",
        instruction="Complete with the Present Perfect form of the verb.",
        question="She ___ (write) five emails today.",
        options=None,
        correct_answer="has written",
        accepted_answers=["has wrote"],
        explanation="She + has + written.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_affirmative_07",
        topic="affirmative",
        question_type="fill_blank",
        instruction="Complete with the Present Perfect form of the verb.",
        question="They ___ (live) here since 2019.",
        options=None,
        correct_answer="have lived",
        accepted_answers=["have been living"],
        explanation="They + have + lived.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_affirmative_08",
        topic="affirmative",
        question_type="fill_blank",
        instruction="Complete with the Present Perfect form of the verb.",
        question="I ___ (lose) my keys.",
        options=None,
        correct_answer="have lost",
        accepted_answers=[],
        explanation="I + have + lost.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_affirmative_09",
        topic="affirmative",
        question_type="fill_blank",
        instruction="Complete with the Present Perfect form of the verb.",
        question="My parents ___ (buy) a new car.",
        options=None,
        correct_answer="have bought",
        accepted_answers=[],
        explanation="Parents = they → have bought.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_affirmative_10",
        topic="affirmative",
        question_type="fill_blank",
        instruction="Complete with the Present Perfect form of the verb.",
        question="He ___ (break) his phone twice this month.",
        options=None,
        correct_answer="has broken",
        accepted_answers=["has broke"],
        explanation="He + has + broken.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_affirmative_11",
        topic="affirmative",
        question_type="transform_sentence",
        instruction="Rewrite the sentence in the Present Perfect.",
        question="Rewrite in Present Perfect: She finishes the project.",
        options=None,
        correct_answer="She has finished the project.",
        accepted_answers=["She's finished the project."],
        explanation="Change finishes → has finished.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_affirmative_12",
        topic="affirmative",
        question_type="transform_sentence",
        instruction="Rewrite the sentence in the Present Perfect.",
        question="Rewrite in Present Perfect: They visit London.",
        options=None,
        correct_answer="They have visited London.",
        accepted_answers=["They've visited London."],
        explanation="Change visit → have visited.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_affirmative_13",
        topic="affirmative",
        question_type="transform_sentence",
        instruction="Rewrite the sentence in the Present Perfect.",
        question="Rewrite in Present Perfect: I see that film.",
        options=None,
        correct_answer="I have seen that film.",
        accepted_answers=["I've seen that film.", "I have seen that movie."],
        explanation="Change see → have seen.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_affirmative_14",
        topic="affirmative",
        question_type="transform_sentence",
        instruction="Rewrite the sentence in the Present Perfect.",
        question="Rewrite in Present Perfect: He goes to the gym.",
        options=None,
        correct_answer="He has gone to the gym.",
        accepted_answers=["He's gone to the gym."],
        explanation="Change goes → has gone.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_affirmative_15",
        topic="affirmative",
        question_type="transform_sentence",
        instruction="Rewrite the sentence in the Present Perfect.",
        question="Rewrite in Present Perfect: We eat breakfast.",
        options=None,
        correct_answer="We have eaten breakfast.",
        accepted_answers=["We've eaten breakfast."],
        explanation="Change eat → have eaten.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_negative_01",
        topic="negative",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="Choose the correct negative sentence.",
        options=[
            "She hasn't finished yet.",
            "She haven't finished yet.",
            "She doesn't has finished yet.",
            "She not has finished yet.",
        ],
        correct_answer="She hasn't finished yet.",
        accepted_answers=[],
        explanation="Negative Present Perfect: hasn't / haven't + past participle.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_negative_02",
        topic="negative",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="They ___ never ___ to Japan.",
        options=["have / been", "has / been", "have / went", "did / been"],
        correct_answer="have / been",
        accepted_answers=[],
        explanation="They + have never been.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_negative_03",
        topic="negative",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="I ___ my homework yet.",
        options=["haven't done", "hasn't done", "didn't done", "don't have done"],
        correct_answer="haven't done",
        accepted_answers=[],
        explanation="I + haven't + done.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_negative_04",
        topic="negative",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="He ___ the news.",
        options=["hasn't heard", "haven't heard", "didn't heard", "not has heard"],
        correct_answer="hasn't heard",
        accepted_answers=[],
        explanation="He + hasn't + heard.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_negative_05",
        topic="negative",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="We ___ that restaurant.",
        options=["haven't tried", "hasn't tried", "didn't tried", "aren't tried"],
        correct_answer="haven't tried",
        accepted_answers=[],
        explanation="We + haven't + tried.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_negative_06",
        topic="negative",
        question_type="fill_blank",
        instruction="Complete with the negative Present Perfect.",
        question="She ___ (not / call) me this week.",
        options=None,
        correct_answer="hasn't called",
        accepted_answers=["has not called"],
        explanation="She + hasn't called.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_negative_07",
        topic="negative",
        question_type="fill_blank",
        instruction="Complete with the negative Present Perfect.",
        question="I ___ (not / see) him since Monday.",
        options=None,
        correct_answer="haven't seen",
        accepted_answers=["have not seen"],
        explanation="I + haven't seen.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_negative_08",
        topic="negative",
        question_type="fill_blank",
        instruction="Complete with the negative Present Perfect.",
        question="They ___ (not / finish) the report yet.",
        options=None,
        correct_answer="haven't finished",
        accepted_answers=["have not finished"],
        explanation="They + haven't finished.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_negative_09",
        topic="negative",
        question_type="fill_blank",
        instruction="Complete with the negative Present Perfect.",
        question="Tom ___ (not / eat) all day.",
        options=None,
        correct_answer="hasn't eaten",
        accepted_answers=["has not eaten"],
        explanation="Tom + hasn't eaten.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_negative_10",
        topic="negative",
        question_type="fill_blank",
        instruction="Complete with the negative Present Perfect.",
        question="We ___ (not / meet) before.",
        options=None,
        correct_answer="haven't met",
        accepted_answers=["have not met"],
        explanation="We + haven't met.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_negative_11",
        topic="negative",
        question_type="transform_sentence",
        instruction="Rewrite as a negative Present Perfect sentence.",
        question="Make negative: She has visited Rome.",
        options=None,
        correct_answer="She hasn't visited Rome.",
        accepted_answers=["She has not visited Rome."],
        explanation="Add not → hasn't.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_negative_12",
        topic="negative",
        question_type="transform_sentence",
        instruction="Rewrite as a negative Present Perfect sentence.",
        question="Make negative: They have finished.",
        options=None,
        correct_answer="They haven't finished.",
        accepted_answers=["They have not finished."],
        explanation="Add not → haven't.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_negative_13",
        topic="negative",
        question_type="transform_sentence",
        instruction="Rewrite as a negative Present Perfect sentence.",
        question="Make negative: I have seen her.",
        options=None,
        correct_answer="I haven't seen her.",
        accepted_answers=["I have not seen her."],
        explanation="Add not → haven't.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_negative_14",
        topic="negative",
        question_type="transform_sentence",
        instruction="Rewrite as a negative Present Perfect sentence.",
        question="Make negative: He has done his homework.",
        options=None,
        correct_answer="He hasn't done his homework.",
        accepted_answers=["He has not done his homework."],
        explanation="Add not → hasn't.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_negative_15",
        topic="negative",
        question_type="transform_sentence",
        instruction="Rewrite as a negative Present Perfect sentence.",
        question="Make negative: We have started the project.",
        options=None,
        correct_answer="We haven't started the project.",
        accepted_answers=["We have not started the project."],
        explanation="Add not → haven't.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_interrogative_01",
        topic="interrogative",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="Choose the correct question.",
        options=[
            "Have you ever been to Spain?",
            "Has you ever been to Spain?",
            "Did you ever been to Spain?",
            "Have you ever went to Spain?",
        ],
        correct_answer="Have you ever been to Spain?",
        accepted_answers=[],
        explanation="Questions: Have/Has + subject + past participle.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_interrogative_02",
        topic="interrogative",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="___ she ___ the email yet?",
        options=["Has / read", "Have / read", "Did / read", "Has / reading"],
        correct_answer="Has / read",
        accepted_answers=[],
        explanation="She → Has + past participle.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_interrogative_03",
        topic="interrogative",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="___ they ___ lunch?",
        options=["Have / had", "Has / had", "Did / had", "Have / have"],
        correct_answer="Have / had",
        accepted_answers=[],
        explanation="They → Have + had.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_interrogative_04",
        topic="interrogative",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="Where ___ you ___?",
        options=["have / been", "has / been", "did / been", "are / been"],
        correct_answer="have / been",
        accepted_answers=[],
        explanation="You → have been.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_interrogative_05",
        topic="interrogative",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="How long ___ he ___ here?",
        options=["has / lived", "have / lived", "did / live", "is / lived"],
        correct_answer="has / lived",
        accepted_answers=[],
        explanation="He → has lived.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_interrogative_06",
        topic="interrogative",
        question_type="fill_blank",
        instruction="Complete the Present Perfect question.",
        question="___ you ever ___ sushi? (eat)",
        options=None,
        correct_answer="Have you ever eaten",
        accepted_answers=["Have you eaten"],
        explanation="Have + you + eaten.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_interrogative_07",
        topic="interrogative",
        question_type="fill_blank",
        instruction="Complete the Present Perfect question.",
        question="___ she ___ the news? (hear)",
        options=None,
        correct_answer="Has she heard",
        accepted_answers=[],
        explanation="Has + she + heard.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_interrogative_08",
        topic="interrogative",
        question_type="fill_blank",
        instruction="Complete the Present Perfect question.",
        question="___ they ___ yet? (arrive)",
        options=None,
        correct_answer="Have they arrived",
        accepted_answers=[],
        explanation="Have + they + arrived.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_interrogative_09",
        topic="interrogative",
        question_type="fill_blank",
        instruction="Complete the Present Perfect question.",
        question="How long ___ you ___ English? (study)",
        options=None,
        correct_answer="have you studied",
        accepted_answers=["have you been studying"],
        explanation="have + you + studied.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_interrogative_10",
        topic="interrogative",
        question_type="fill_blank",
        instruction="Complete the Present Perfect question.",
        question="___ he ___ his keys? (find)",
        options=None,
        correct_answer="Has he found",
        accepted_answers=[],
        explanation="Has + he + found.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_interrogative_11",
        topic="interrogative",
        question_type="transform_sentence",
        instruction="Rewrite as a Present Perfect question.",
        question="Make a question: You have finished.",
        options=None,
        correct_answer="Have you finished?",
        accepted_answers=["Have you finished"],
        explanation="Invert: Have + you + finished?",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_interrogative_12",
        topic="interrogative",
        question_type="transform_sentence",
        instruction="Rewrite as a Present Perfect question.",
        question="Make a question: She has called.",
        options=None,
        correct_answer="Has she called?",
        accepted_answers=["Has she called"],
        explanation="Invert: Has + she + called?",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_interrogative_13",
        topic="interrogative",
        question_type="transform_sentence",
        instruction="Rewrite as a Present Perfect question.",
        question="Make a question: They have left.",
        options=None,
        correct_answer="Have they left?",
        accepted_answers=["Have they left"],
        explanation="Invert: Have + they + left?",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_interrogative_14",
        topic="interrogative",
        question_type="transform_sentence",
        instruction="Rewrite as a Present Perfect question.",
        question="Make a question: He has seen the movie.",
        options=None,
        correct_answer="Has he seen the movie?",
        accepted_answers=["Has he seen the movie"],
        explanation="Invert: Has + he + seen...?",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_interrogative_15",
        topic="interrogative",
        question_type="transform_sentence",
        instruction="Rewrite as a Present Perfect question.",
        question="Make a question: We have met before.",
        options=None,
        correct_answer="Have we met before?",
        accepted_answers=["Have we met before"],
        explanation="Invert: Have + we + met...?",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_short_answers_01",
        topic="short_answers",
        question_type="multiple_choice",
        instruction="Choose the correct short answer.",
        question="Have you finished? — ___",
        options=["Yes, I have.", "Yes, I has.", "Yes, I do.", "Yes, I finished."],
        correct_answer="Yes, I have.",
        accepted_answers=[],
        explanation="Short answer: Yes, I have. / No, I haven't.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_short_answers_02",
        topic="short_answers",
        question_type="multiple_choice",
        instruction="Choose the correct short answer.",
        question="Has she arrived? — ___",
        options=["Yes, she has.", "Yes, she have.", "Yes, she does.", "Yes, she arrived."],
        correct_answer="Yes, she has.",
        accepted_answers=[],
        explanation="She → Yes, she has.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_short_answers_03",
        topic="short_answers",
        question_type="multiple_choice",
        instruction="Choose the correct short answer.",
        question="Have they called? — ___",
        options=["No, they haven't.", "No, they hasn't.", "No, they don't.", "No, they didn't."],
        correct_answer="No, they haven't.",
        accepted_answers=[],
        explanation="They → No, they haven't.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_short_answers_04",
        topic="short_answers",
        question_type="multiple_choice",
        instruction="Choose the correct short answer.",
        question="Has he eaten? — ___",
        options=["No, he hasn't.", "No, he haven't.", "No, he doesn't.", "No, he didn't."],
        correct_answer="No, he hasn't.",
        accepted_answers=[],
        explanation="He → No, he hasn't.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_short_answers_05",
        topic="short_answers",
        question_type="multiple_choice",
        instruction="Choose the correct short answer.",
        question="Have we met? — ___",
        options=["Yes, we have.", "Yes, we has.", "Yes, we do.", "Yes, we met."],
        correct_answer="Yes, we have.",
        accepted_answers=[],
        explanation="We → Yes, we have.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_short_answers_06",
        topic="short_answers",
        question_type="multiple_choice",
        instruction="Choose the correct short answer.",
        question="Has Tom left? — ___",
        options=["Yes, he has.", "Yes, he have.", "Yes, Tom have.", "Yes, he does."],
        correct_answer="Yes, he has.",
        accepted_answers=[],
        explanation="Tom → he → Yes, he has.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_short_answers_07",
        topic="short_answers",
        question_type="multiple_choice",
        instruction="Choose the correct short answer.",
        question="Have you seen her? — ___",
        options=["No, I haven't.", "No, I hasn't.", "No, I don't.", "No, I didn't."],
        correct_answer="No, I haven't.",
        accepted_answers=[],
        explanation="I → No, I haven't.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_short_answers_08",
        topic="short_answers",
        question_type="short_answer",
        instruction="Complete the short answer.",
        question="Have you done it? — Yes, I ___.",
        options=None,
        correct_answer="have",
        accepted_answers=[],
        explanation="Affirmative short answer with have.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_short_answers_09",
        topic="short_answers",
        question_type="short_answer",
        instruction="Complete the short answer.",
        question="Has she called? — No, she ___.",
        options=None,
        correct_answer="hasn't",
        accepted_answers=["has not"],
        explanation="Negative short answer with hasn't.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_short_answers_10",
        topic="short_answers",
        question_type="short_answer",
        instruction="Complete the short answer.",
        question="Have they finished? — Yes, they ___.",
        options=None,
        correct_answer="have",
        accepted_answers=[],
        explanation="They → have.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_short_answers_11",
        topic="short_answers",
        question_type="short_answer",
        instruction="Complete the short answer.",
        question="Has he arrived? — No, he ___.",
        options=None,
        correct_answer="hasn't",
        accepted_answers=["has not"],
        explanation="He → hasn't.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_short_answers_12",
        topic="short_answers",
        question_type="short_answer",
        instruction="Complete the short answer.",
        question="Have we started? — Yes, we ___.",
        options=None,
        correct_answer="have",
        accepted_answers=[],
        explanation="We → have.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_short_answers_13",
        topic="short_answers",
        question_type="short_answer",
        instruction="Complete the short answer.",
        question="Has Ana left? — Yes, she ___.",
        options=None,
        correct_answer="has",
        accepted_answers=[],
        explanation="Ana → she → has.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_short_answers_14",
        topic="short_answers",
        question_type="short_answer",
        instruction="Complete the short answer.",
        question="Have you eaten? — No, I ___.",
        options=None,
        correct_answer="haven't",
        accepted_answers=["have not"],
        explanation="I → haven't.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_identify_01",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct past participle.",
        question="What is the past participle of go?",
        options=["gone", "went", "goed", "going"],
        correct_answer="gone",
        accepted_answers=[],
        explanation="go → went → gone.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_identify_02",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct past participle.",
        question="What is the past participle of write?",
        options=["written", "wrote", "writed", "writing"],
        correct_answer="written",
        accepted_answers=[],
        explanation="write → wrote → written.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_identify_03",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct past participle.",
        question="What is the past participle of see?",
        options=["seen", "saw", "seed", "seeing"],
        correct_answer="seen",
        accepted_answers=[],
        explanation="see → saw → seen.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_identify_04",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct past participle.",
        question="What is the past participle of eat?",
        options=["eaten", "ate", "eated", "eating"],
        correct_answer="eaten",
        accepted_answers=[],
        explanation="eat → ate → eaten.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_identify_05",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct past participle.",
        question="What is the past participle of take?",
        options=["taken", "took", "taked", "taking"],
        correct_answer="taken",
        accepted_answers=[],
        explanation="take → took → taken.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_identify_06",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct past participle.",
        question="What is the past participle of do?",
        options=["done", "did", "doed", "doing"],
        correct_answer="done",
        accepted_answers=[],
        explanation="do → did → done.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_identify_07",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct past participle.",
        question="What is the past participle of break?",
        options=["broken", "broke", "breaked", "breaking"],
        correct_answer="broken",
        accepted_answers=[],
        explanation="break → broke → broken.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_identify_08",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct option.",
        question="Which sentence uses the Present Perfect?",
        options=[
            "I have lived here for five years.",
            "I lived here for five years.",
            "I am living here for five years.",
            "I live here for five years.",
        ],
        correct_answer="I have lived here for five years.",
        accepted_answers=[],
        explanation="Present Perfect = have/has + past participle.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_identify_09",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct option.",
        question="Which time expression is typical with Present Perfect?",
        options=["already", "yesterday", "last week", "two days ago"],
        correct_answer="already",
        accepted_answers=[],
        explanation=(
            "already / yet / just / ever / never / since / for often go with Present Perfect."
        ),
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_identify_10",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct option.",
        question="Choose the irregular past participle.",
        options=["spoken", "talked", "played", "wanted"],
        correct_answer="spoken",
        accepted_answers=[],
        explanation="speak → spoke → spoken is irregular.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_identify_11",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct option.",
        question="Which verb form completes: She has ___ the book.",
        options=["read", "reads", "reading", "readed"],
        correct_answer="read",
        accepted_answers=[],
        explanation="read (past participle) after has.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_identify_12",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct option.",
        question="Identify the correct form: They have ___ the window.",
        options=["broken", "broke", "break", "breaking"],
        correct_answer="broken",
        accepted_answers=[],
        explanation="have + broken.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_identify_13",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct option.",
        question="Which sentence is Present Perfect continuous idea with for/since often paired?",
        options=[
            "I have known her since 2018.",
            "I knew her since 2018.",
            "I know her since 2018.",
            "I am knowing her since 2018.",
        ],
        correct_answer="I have known her since 2018.",
        accepted_answers=[],
        explanation="State verbs like know use Present Perfect with since.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_identify_14",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct option.",
        question="Choose the sentence with yet.",
        options=[
            "Has she arrived yet?",
            "Has she arrived yesterday?",
            "Has she arrived last night?",
            "Has she arrived two hours ago?",
        ],
        correct_answer="Has she arrived yet?",
        accepted_answers=[],
        explanation="yet is common in Present Perfect questions/negatives.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_order_words_01",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make an affirmative sentence.",
        question="she / has / finished / already / the report",
        options=None,
        correct_answer="She has already finished the report.",
        accepted_answers=["She has finished the report already."],
        explanation="Subject + has + already + past participle.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_order_words_02",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="you / have / ever / been / to Canada",
        options=None,
        correct_answer="Have you ever been to Canada?",
        accepted_answers=[],
        explanation="Have + subject + ever + been...?",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_order_words_03",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make a negative sentence.",
        question="they / have / not / seen / the movie / yet",
        options=None,
        correct_answer="They have not seen the movie yet.",
        accepted_answers=["They haven't seen the movie yet."],
        explanation="have not + past participle + yet.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_order_words_04",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make an affirmative sentence.",
        question="he / has / lived / here / for / ten years",
        options=None,
        correct_answer="He has lived here for ten years.",
        accepted_answers=[],
        explanation="has lived + for + time.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_order_words_05",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make an affirmative sentence.",
        question="I / have / just / arrived",
        options=None,
        correct_answer="I have just arrived.",
        accepted_answers=["I've just arrived."],
        explanation="have + just + past participle.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_order_words_06",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="has / she / called / you / yet",
        options=None,
        correct_answer="Has she called you yet?",
        accepted_answers=[],
        explanation="Has + she + called + yet?",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_order_words_07",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make an affirmative sentence.",
        question="we / have / known / each other / since / 2015",
        options=None,
        correct_answer="We have known each other since 2015.",
        accepted_answers=[],
        explanation="have known + since + point in time.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_order_words_08",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make an affirmative sentence.",
        question="they / have / already / left",
        options=None,
        correct_answer="They have already left.",
        accepted_answers=["They've already left."],
        explanation="have + already + left.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_order_words_09",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="have / you / done / your homework",
        options=None,
        correct_answer="Have you done your homework?",
        accepted_answers=[],
        explanation="Have + you + done...?",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_order_words_10",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make an affirmative sentence.",
        question="she / has / never / eaten / sushi",
        options=None,
        correct_answer="She has never eaten sushi.",
        accepted_answers=[],
        explanation="has + never + eaten.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_order_words_11",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make an affirmative sentence.",
        question="I / have / lost / my wallet",
        options=None,
        correct_answer="I have lost my wallet.",
        accepted_answers=["I've lost my wallet."],
        explanation="have + lost.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_order_words_12",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="has / Tom / finished / yet",
        options=None,
        correct_answer="Has Tom finished yet?",
        accepted_answers=[],
        explanation="Has + Tom + finished + yet?",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_order_words_13",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make a negative sentence.",
        question="we / haven't / met / before",
        options=None,
        correct_answer="We haven't met before.",
        accepted_answers=["We have not met before."],
        explanation="haven't + met.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_order_words_14",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make an affirmative sentence.",
        question="they / have / bought / a new house",
        options=None,
        correct_answer="They have bought a new house.",
        accepted_answers=["They've bought a new house."],
        explanation="have + bought.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_sentences_01",
        topic="sentences",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="Choose the correct sentence.",
        options=[
            "I have lived here for three years.",
            "I have lived here since three years.",
            "I live here for three years.",
            "I lived here since three years.",
        ],
        correct_answer="I have lived here for three years.",
        accepted_answers=[],
        explanation="for + period of time; since + starting point.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_sentences_02",
        topic="sentences",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="She has worked here ___ 2020.",
        options=["since", "for", "ago", "from"],
        correct_answer="since",
        accepted_answers=[],
        explanation="since + year/point in time.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_sentences_03",
        topic="sentences",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="They have been married ___ ten years.",
        options=["for", "since", "ago", "during"],
        correct_answer="for",
        accepted_answers=[],
        explanation="for + duration.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_sentences_04",
        topic="sentences",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="I have ___ finished my work.",
        options=["just", "yesterday", "ago", "last night"],
        correct_answer="just",
        accepted_answers=[],
        explanation="just = a very short time ago with Present Perfect.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_sentences_05",
        topic="sentences",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="Have you finished ___?",
        options=["yet", "already ago", "yesterday", "last week"],
        correct_answer="yet",
        accepted_answers=[],
        explanation="yet often ends Present Perfect questions.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_sentences_06",
        topic="sentences",
        question_type="fill_blank",
        instruction="Complete the sentence.",
        question="I have known her ___ 2018. (since/for)",
        options=None,
        correct_answer="since",
        accepted_answers=[],
        explanation="since + starting point.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_sentences_07",
        topic="sentences",
        question_type="fill_blank",
        instruction="Complete the sentence.",
        question="We have waited ___ two hours. (since/for)",
        options=None,
        correct_answer="for",
        accepted_answers=[],
        explanation="for + duration.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_sentences_08",
        topic="sentences",
        question_type="fill_blank",
        instruction="Complete the sentence.",
        question="He has ___ left. (just/yet)",
        options=None,
        correct_answer="just",
        accepted_answers=[],
        explanation="just before the past participle.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_sentences_09",
        topic="sentences",
        question_type="fill_blank",
        instruction="Complete the sentence.",
        question="She hasn't called ___ . (yet/since)",
        options=None,
        correct_answer="yet",
        accepted_answers=[],
        explanation="yet in negatives.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_sentences_10",
        topic="sentences",
        question_type="fill_blank",
        instruction="Complete the sentence.",
        question="___ you ever ___ to London? (be)",
        options=None,
        correct_answer="Have / been",
        accepted_answers=["Have you ever been"],
        explanation="Have + ever + been.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_sentences_11",
        topic="sentences",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="Choose been or gone: She has ___ to the store. She is still there.",
        options=["gone", "been", "went", "going"],
        correct_answer="gone",
        accepted_answers=[],
        explanation="gone = went and is still away; been = went and returned.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_sentences_12",
        topic="sentences",
        question_type="multiple_choice",
        instruction="Choose the correct option.",
        question="Choose been or gone: I have ___ to Italy twice. I'm home now.",
        options=["been", "gone", "went", "going"],
        correct_answer="been",
        accepted_answers=[],
        explanation="been = experience; subject is back.",
    ),
    PresentPerfectQuestionSeed(
        stable_key="present_perfect_sentences_13",
        topic="sentences",
        question_type="transform_sentence",
        instruction="Rewrite using Present Perfect.",
        question="Rewrite using Present Perfect with already: She finished her homework.",
        options=None,
        correct_answer="She has already finished her homework.",
        accepted_answers=[
            "She's already finished her homework.",
            "She has finished her homework already.",
        ],
        explanation="already + Present Perfect.",
    ),
]
