"""Banco inicial de preguntas para el examen Present Simple."""

from dataclasses import dataclass


@dataclass(frozen=True)
class PresentSimpleQuestionSeed:
    stable_key: str
    topic: str
    question_type: str
    instruction: str
    question: str
    options: list[str] | None
    correct_answer: str
    accepted_answers: list[str]
    explanation: str
    points: int = 1
    active: bool = True


PRESENT_SIMPLE_QUESTIONS: list[PresentSimpleQuestionSeed] = [
    # Afirmativas
    PresentSimpleQuestionSeed(
        stable_key="present_simple_affirmative_01",
        topic="affirmative",
        question_type="multiple_choice",
        instruction="Choose the correct sentence.",
        question="Which sentence is correct in the Present Simple?",
        options=[
            "She play tennis every Saturday.",
            "She plays tennis every Saturday.",
            "She playing tennis every Saturday.",
            "She do play tennis every Saturday.",
        ],
        correct_answer="She plays tennis every Saturday.",
        accepted_answers=[],
        explanation=(
            "With he, she, and it, add -s to the verb in affirmative Present Simple: plays."
        ),
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_affirmative_02",
        topic="affirmative",
        question_type="fill_blank",
        instruction="Complete the sentence with the correct Present Simple form.",
        question="My brother ___ to school by bus. (go)",
        options=None,
        correct_answer="goes",
        accepted_answers=[],
        explanation=(
            "Go becomes goes with he/she/it. Remember: go → goes (add -es after o)."
        ),
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_affirmative_03",
        topic="affirmative",
        question_type="fill_blank",
        instruction="Complete the sentence with the correct Present Simple form.",
        question="We ___ English every day. (study)",
        options=None,
        correct_answer="study",
        accepted_answers=[],
        explanation=(
            "With I, you, we, and they, use the base form of the verb: study (no -s)."
        ),
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_affirmative_04",
        topic="affirmative",
        question_type="multiple_choice",
        instruction="Choose the correct verb form.",
        question="Tom ___ breakfast at 7:00 every morning.",
        options=["eat", "eats", "eating", "do eat"],
        correct_answer="eats",
        accepted_answers=[],
        explanation="Tom is he, so the Present Simple verb needs -s: eats.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_affirmative_05",
        topic="affirmative",
        question_type="transform_sentence",
        instruction="Write the sentence in the Present Simple affirmative.",
        question="(she / watch) TV after dinner.",
        options=None,
        correct_answer="She watches TV after dinner.",
        accepted_answers=["She watches TV after dinner"],
        explanation=(
            "With she, watch becomes watches (add -es after ch). Capitalize the first word."
        ),
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_affirmative_06",
        topic="affirmative",
        question_type="fill_blank",
        instruction="Complete the sentence with the correct Present Simple form.",
        question="Anna ___ her homework after school. (do)",
        options=None,
        correct_answer="does",
        accepted_answers=[],
        explanation="Do becomes does with he/she/it.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_affirmative_07",
        topic="affirmative",
        question_type="multiple_choice",
        instruction="Choose the correct sentence.",
        question="Which sentence is correct?",
        options=[
            "They watches movies on Fridays.",
            "They watch movies on Fridays.",
            "They watching movies on Fridays.",
            "They does watch movies on Fridays.",
        ],
        correct_answer="They watch movies on Fridays.",
        accepted_answers=[],
        explanation="With they, use the base form watch (no -s).",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_affirmative_08",
        topic="affirmative",
        question_type="fill_blank",
        instruction="Complete the sentence with the correct Present Simple form.",
        question="The baby ___ a lot at night. (cry)",
        options=None,
        correct_answer="cries",
        accepted_answers=[],
        explanation="For verbs ending in consonant + y, change y to i and add -es: cry → cries.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_affirmative_09",
        topic="affirmative",
        question_type="multiple_choice",
        instruction="Choose the correct verb form.",
        question="My father ___ the newspaper every Sunday.",
        options=["read", "reads", "reading", "do read"],
        correct_answer="reads",
        accepted_answers=[],
        explanation="My father is he, so add -s: reads.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_affirmative_10",
        topic="affirmative",
        question_type="transform_sentence",
        instruction="Write the sentence in the Present Simple affirmative.",
        question="(I / live) near the park.",
        options=None,
        correct_answer="I live near the park.",
        accepted_answers=["I live near the park"],
        explanation="With I, use the base form live (no -s).",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_affirmative_11",
        topic="affirmative",
        question_type="fill_blank",
        instruction="Complete the sentence with the correct Present Simple form.",
        question="She ___ Spanish and English. (speak)",
        options=None,
        correct_answer="speaks",
        accepted_answers=[],
        explanation="With she, add -s to the verb: speaks.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_affirmative_12",
        topic="affirmative",
        question_type="multiple_choice",
        instruction="Choose the correct sentence.",
        question="Which sentence uses the third person correctly?",
        options=[
            "He teach math at the university.",
            "He teaches math at the university.",
            "He teaching math at the university.",
            "He do teach math at the university.",
        ],
        correct_answer="He teaches math at the university.",
        accepted_answers=[],
        explanation="Teach ends in -ch, so add -es: teaches.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_affirmative_13",
        topic="affirmative",
        question_type="fill_blank",
        instruction="Complete the sentence with the correct Present Simple form.",
        question="You ___ very hard every day. (work)",
        options=None,
        correct_answer="work",
        accepted_answers=[],
        explanation="With you, use the base form work (no -s).",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_affirmative_14",
        topic="affirmative",
        question_type="transform_sentence",
        instruction="Write the sentence in the Present Simple affirmative.",
        question="(it / rain) a lot in April.",
        options=None,
        correct_answer="It rains a lot in April.",
        accepted_answers=["It rains a lot in April"],
        explanation="With it, add -s to the verb: rains.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_affirmative_15",
        topic="affirmative",
        question_type="multiple_choice",
        instruction="Choose the correct verb form.",
        question="My sister ___ the piano every afternoon.",
        options=["practice", "practices", "practicing", "do practice"],
        correct_answer="practices",
        accepted_answers=[],
        explanation="My sister is she, so use practices.",
    ),
    # Negativas
    PresentSimpleQuestionSeed(
        stable_key="present_simple_negative_01",
        topic="negative",
        question_type="multiple_choice",
        instruction="Choose the correct negative sentence.",
        question="Which sentence is correct?",
        options=[
            "She doesn't likes coffee.",
            "She don't like coffee.",
            "She doesn't like coffee.",
            "She not like coffee.",
        ],
        correct_answer="She doesn't like coffee.",
        accepted_answers=[],
        explanation=(
            "Use doesn't with he/she/it, then the base verb like (no -s after doesn't)."
        ),
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_negative_02",
        topic="negative",
        question_type="fill_blank",
        instruction="Complete the sentence with don't or doesn't.",
        question="They ___ live in this city.",
        options=None,
        correct_answer="don't",
        accepted_answers=["do not"],
        explanation="Use don't (do not) with I, you, we, and they.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_negative_03",
        topic="negative",
        question_type="fill_blank",
        instruction="Complete the sentence with don't or doesn't.",
        question="My sister ___ speak French.",
        options=None,
        correct_answer="doesn't",
        accepted_answers=["does not"],
        explanation="My sister is she, so use doesn't (does not) + base verb.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_negative_04",
        topic="negative",
        question_type="transform_sentence",
        instruction="Change the sentence into the Present Simple negative.",
        question="He works on Sundays.",
        options=None,
        correct_answer="He doesn't work on Sundays.",
        accepted_answers=[
            "He does not work on Sundays.",
            "He doesn't work on Sundays",
        ],
        explanation=(
            "Use doesn't + base verb work. Do not keep the -s on the main verb."
        ),
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_negative_05",
        topic="negative",
        question_type="multiple_choice",
        instruction="Choose the correct sentence.",
        question="Which negative sentence is correct?",
        options=[
            "I doesn't eat meat.",
            "I don't eat meat.",
            "I not eat meat.",
            "I don't eats meat.",
        ],
        correct_answer="I don't eat meat.",
        accepted_answers=[],
        explanation="With I, use don't + base verb. Never use doesn't with I.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_negative_06",
        topic="negative",
        question_type="fill_blank",
        instruction="Complete the sentence with don't or doesn't.",
        question="We ___ watch TV in the morning.",
        options=None,
        correct_answer="don't",
        accepted_answers=["do not"],
        explanation="With we, use don't + base verb.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_negative_07",
        topic="negative",
        question_type="transform_sentence",
        instruction="Change the sentence into the Present Simple negative.",
        question="They play soccer after school.",
        options=None,
        correct_answer="They don't play soccer after school.",
        accepted_answers=[
            "They do not play soccer after school.",
            "They don't play soccer after school",
        ],
        explanation="Use don't + base verb play with they.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_negative_08",
        topic="negative",
        question_type="multiple_choice",
        instruction="Choose the correct negative sentence.",
        question="Which sentence is correct?",
        options=[
            "He don't drive to work.",
            "He doesn't drives to work.",
            "He doesn't drive to work.",
            "He not drive to work.",
        ],
        correct_answer="He doesn't drive to work.",
        accepted_answers=[],
        explanation="With he, use doesn't + base verb drive (no -s after doesn't).",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_negative_09",
        topic="negative",
        question_type="fill_blank",
        instruction="Complete the sentence with don't or doesn't.",
        question="The cat ___ like cold water.",
        options=None,
        correct_answer="doesn't",
        accepted_answers=["does not"],
        explanation="The cat is it, so use doesn't + base verb.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_negative_10",
        topic="negative",
        question_type="transform_sentence",
        instruction="Change the sentence into the Present Simple negative.",
        question="Laura studies at night.",
        options=None,
        correct_answer="Laura doesn't study at night.",
        accepted_answers=[
            "Laura does not study at night.",
            "Laura doesn't study at night",
        ],
        explanation="Use doesn't + base verb study. Change studies to study.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_negative_11",
        topic="negative",
        question_type="multiple_choice",
        instruction="Choose the correct sentence.",
        question="Which negative sentence is correct?",
        options=[
            "You doesn't need a ticket.",
            "You don't need a ticket.",
            "You not need a ticket.",
            "You don't needs a ticket.",
        ],
        correct_answer="You don't need a ticket.",
        accepted_answers=[],
        explanation="With you, use don't + base verb need.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_negative_12",
        topic="negative",
        question_type="fill_blank",
        instruction="Complete with the correct negative form (don't/doesn't + verb).",
        question="She ___ pizza. (like)",
        options=None,
        correct_answer="doesn't like",
        accepted_answers=["does not like"],
        explanation="Use doesn't + base verb like with she.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_negative_13",
        topic="negative",
        question_type="transform_sentence",
        instruction="Change the sentence into the Present Simple negative.",
        question="I wake up early on weekends.",
        options=None,
        correct_answer="I don't wake up early on weekends.",
        accepted_answers=[
            "I do not wake up early on weekends.",
            "I don't wake up early on weekends",
        ],
        explanation="With I, use don't + base verb wake.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_negative_14",
        topic="negative",
        question_type="multiple_choice",
        instruction="Choose the correct negative sentence.",
        question="Which sentence is correct?",
        options=[
            "My parents doesn't cook dinner.",
            "My parents don't cook dinner.",
            "My parents not cook dinner.",
            "My parents don't cooks dinner.",
        ],
        correct_answer="My parents don't cook dinner.",
        accepted_answers=[],
        explanation="My parents is they, so use don't + base verb cook.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_negative_15",
        topic="negative",
        question_type="fill_blank",
        instruction="Complete the sentence with don't or doesn't.",
        question="Peter ___ play the guitar.",
        options=None,
        correct_answer="doesn't",
        accepted_answers=["does not"],
        explanation="Peter is he, so use doesn't + base verb.",
    ),
    # Interrogativas
    PresentSimpleQuestionSeed(
        stable_key="present_simple_interrogative_01",
        topic="interrogative",
        question_type="multiple_choice",
        instruction="Choose the correct question.",
        question="Which sentence has the correct Present Simple interrogative structure?",
        options=[
            "You do live here?",
            "Do you live here?",
            "Does you live here?",
            "Live you here?",
        ],
        correct_answer="Do you live here?",
        accepted_answers=[],
        explanation="Present Simple questions use: Do/Does + subject + base verb.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_interrogative_02",
        topic="interrogative",
        question_type="multiple_choice",
        instruction="Choose the correct question.",
        question="Which question is correct?",
        options=[
            "Does she plays the piano?",
            "Do she play the piano?",
            "Does she play the piano?",
            "She does play the piano?",
        ],
        correct_answer="Does she play the piano?",
        accepted_answers=[],
        explanation=(
            "Use does with she, then the base verb play (no -s after does)."
        ),
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_interrogative_03",
        topic="interrogative",
        question_type="fill_blank",
        instruction="Complete the question with Do or Does.",
        question="___ your parents work in the hospital?",
        options=None,
        correct_answer="Do",
        accepted_answers=["do"],
        explanation="Your parents is they, so use Do before the subject.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_interrogative_04",
        topic="interrogative",
        question_type="transform_sentence",
        instruction="Change the sentence into a Present Simple question.",
        question="Maria studies math at night.",
        options=None,
        correct_answer="Does Maria study math at night?",
        accepted_answers=["Does Maria study maths at night?"],
        explanation=(
            "Use Does + subject + base verb study. Change studies to study."
        ),
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_interrogative_05",
        topic="interrogative",
        question_type="fill_blank",
        instruction="Complete the question with Do or Does.",
        question="___ he like spicy food?",
        options=None,
        correct_answer="Does",
        accepted_answers=["does"],
        explanation="Use Does with he, she, and it.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_interrogative_06",
        topic="interrogative",
        question_type="multiple_choice",
        instruction="Choose the correct question.",
        question="Which question is correct?",
        options=[
            "Do they lives in London?",
            "Does they live in London?",
            "Do they live in London?",
            "They do live in London?",
        ],
        correct_answer="Do they live in London?",
        accepted_answers=[],
        explanation="Use Do with they + base verb live.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_interrogative_07",
        topic="interrogative",
        question_type="transform_sentence",
        instruction="Change the sentence into a Present Simple question.",
        question="You speak English at home.",
        options=None,
        correct_answer="Do you speak English at home?",
        accepted_answers=["Do you speak English at home"],
        explanation="Use Do + you + base verb speak.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_interrogative_08",
        topic="interrogative",
        question_type="fill_blank",
        instruction="Complete the question with Do or Does.",
        question="___ the train leave at 8:00?",
        options=None,
        correct_answer="Does",
        accepted_answers=["does"],
        explanation="The train is it, so use Does + base verb leave.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_interrogative_09",
        topic="interrogative",
        question_type="multiple_choice",
        instruction="Choose the correct question.",
        question="Which question uses does correctly?",
        options=[
            "Does Tom goes to the gym?",
            "Does Tom go to the gym?",
            "Do Tom go to the gym?",
            "Does Tom going to the gym?",
        ],
        correct_answer="Does Tom go to the gym?",
        accepted_answers=[],
        explanation="After does, use the base form go, not goes.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_interrogative_10",
        topic="interrogative",
        question_type="transform_sentence",
        instruction="Change the sentence into a Present Simple question.",
        question="They finish work at six.",
        options=None,
        correct_answer="Do they finish work at six?",
        accepted_answers=["Do they finish work at six"],
        explanation="Use Do + they + base verb finish.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_interrogative_11",
        topic="interrogative",
        question_type="fill_blank",
        instruction="Complete the question with one word.",
        question="Where ___ your sister live?",
        options=None,
        correct_answer="does",
        accepted_answers=["Does"],
        explanation="Your sister is she, so use does after the question word.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_interrogative_12",
        topic="interrogative",
        question_type="multiple_choice",
        instruction="Choose the correct question.",
        question="Which question is correct?",
        options=[
            "Does we need tickets?",
            "Do we need tickets?",
            "Do we needs tickets?",
            "We do need tickets?",
        ],
        correct_answer="Do we need tickets?",
        accepted_answers=[],
        explanation="Use Do with we + base verb need.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_interrogative_13",
        topic="interrogative",
        question_type="transform_sentence",
        instruction="Change the sentence into a Present Simple question.",
        question="The dog sleeps on the sofa.",
        options=None,
        correct_answer="Does the dog sleep on the sofa?",
        accepted_answers=[],
        explanation="The dog is it, so use Does + subject + base verb sleep.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_interrogative_14",
        topic="interrogative",
        question_type="fill_blank",
        instruction="Complete the question with Do or Does.",
        question="___ your friends walk to school?",
        options=None,
        correct_answer="Do",
        accepted_answers=["do"],
        explanation="Your friends is they, so use Do.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_interrogative_15",
        topic="interrogative",
        question_type="multiple_choice",
        instruction="Choose the correct question.",
        question="Which question is correct?",
        options=[
            "What time does she gets up?",
            "What time do she get up?",
            "What time does she get up?",
            "What time she gets up?",
        ],
        correct_answer="What time does she get up?",
        accepted_answers=[],
        explanation="Use does + she + base verb get after the question phrase.",
    ),
    # Respuestas cortas
    PresentSimpleQuestionSeed(
        stable_key="present_simple_short_answers_01",
        topic="short_answers",
        question_type="multiple_choice",
        instruction="Choose the correct short answer.",
        question="Does she play tennis?",
        options=[
            "Yes, she does.",
            "Yes, she plays.",
            "Yes, she do.",
            "Yes, she is.",
        ],
        correct_answer="Yes, she does.",
        accepted_answers=[],
        explanation=(
            "An affirmative short answer uses yes + subject pronoun + do/does."
        ),
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_short_answers_02",
        topic="short_answers",
        question_type="multiple_choice",
        instruction="Choose the correct short answer.",
        question="Do they live near the school?",
        options=[
            "No, they doesn't.",
            "No, they don't.",
            "No, they aren't.",
            "No, they not.",
        ],
        correct_answer="No, they don't.",
        accepted_answers=[],
        explanation="A negative short answer for they uses don't.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_short_answers_03",
        topic="short_answers",
        question_type="short_answer",
        instruction="Write a negative short answer.",
        question="Does Ana speak German?",
        options=None,
        correct_answer="No, she doesn't.",
        accepted_answers=["No, she does not.", "No she doesn't."],
        explanation="Use she for Ana and doesn't (or does not) in a negative short answer.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_short_answers_04",
        topic="short_answers",
        question_type="short_answer",
        instruction="Write an affirmative short answer.",
        question="Do you like chocolate?",
        options=None,
        correct_answer="Yes, I do.",
        accepted_answers=["Yes I do.", "Yes, I do"],
        explanation="With you, the short answer uses I: Yes, I do.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_short_answers_05",
        topic="short_answers",
        question_type="multiple_choice",
        instruction="Choose the correct short answer.",
        question="Does your brother cook dinner?",
        options=[
            "Yes, he do.",
            "Yes, he does.",
            "Yes, he cooks.",
            "Yes, he is.",
        ],
        correct_answer="Yes, he does.",
        accepted_answers=[],
        explanation="Your brother is he, so the affirmative short answer is Yes, he does.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_short_answers_06",
        topic="short_answers",
        question_type="short_answer",
        instruction="Write an affirmative short answer.",
        question="Do we need umbrellas?",
        options=None,
        correct_answer="Yes, we do.",
        accepted_answers=["Yes we do.", "Yes, we do"],
        explanation="With we, the affirmative short answer is Yes, we do.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_short_answers_07",
        topic="short_answers",
        question_type="multiple_choice",
        instruction="Choose the correct short answer.",
        question="Does it rain a lot here?",
        options=[
            "Yes, it do.",
            "Yes, it rains.",
            "Yes, it does.",
            "Yes, it is.",
        ],
        correct_answer="Yes, it does.",
        accepted_answers=[],
        explanation="For it, the affirmative short answer is Yes, it does.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_short_answers_08",
        topic="short_answers",
        question_type="short_answer",
        instruction="Write a negative short answer.",
        question="Do your parents work on Sundays?",
        options=None,
        correct_answer="No, they don't.",
        accepted_answers=["No, they do not.", "No they don't."],
        explanation="Your parents is they, so use No, they don't.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_short_answers_09",
        topic="short_answers",
        question_type="multiple_choice",
        instruction="Choose the correct short answer.",
        question="Do I need a passport?",
        options=[
            "Yes, you does.",
            "Yes, you do.",
            "Yes, you need.",
            "Yes, you are.",
        ],
        correct_answer="Yes, you do.",
        accepted_answers=[],
        explanation="The short answer to Do I…? uses you: Yes, you do.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_short_answers_10",
        topic="short_answers",
        question_type="short_answer",
        instruction="Write a negative short answer.",
        question="Does Tom play basketball?",
        options=None,
        correct_answer="No, he doesn't.",
        accepted_answers=["No, he does not.", "No he doesn't."],
        explanation="Tom is he, so use No, he doesn't.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_short_answers_11",
        topic="short_answers",
        question_type="multiple_choice",
        instruction="Choose the correct short answer.",
        question="Do your friends like pizza?",
        options=[
            "Yes, they does.",
            "Yes, they like.",
            "Yes, they do.",
            "Yes, they are.",
        ],
        correct_answer="Yes, they do.",
        accepted_answers=[],
        explanation="Your friends is they, so use Yes, they do.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_short_answers_12",
        topic="short_answers",
        question_type="short_answer",
        instruction="Write an affirmative short answer.",
        question="Does your mother drive to work?",
        options=None,
        correct_answer="Yes, she does.",
        accepted_answers=["Yes she does.", "Yes, she does"],
        explanation="Your mother is she, so use Yes, she does.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_short_answers_13",
        topic="short_answers",
        question_type="multiple_choice",
        instruction="Choose the correct short answer.",
        question="Does he speak Japanese?",
        options=[
            "No, he don't.",
            "No, he doesn't.",
            "No, he not.",
            "No, he isn't.",
        ],
        correct_answer="No, he doesn't.",
        accepted_answers=[],
        explanation="A negative short answer for he uses doesn't.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_short_answers_14",
        topic="short_answers",
        question_type="short_answer",
        instruction="Write a negative short answer.",
        question="Do you study on Fridays?",
        options=None,
        correct_answer="No, I don't.",
        accepted_answers=["No, I do not.", "No I don't."],
        explanation="With you, the negative short answer uses I: No, I don't.",
    ),
    # Identificar
    PresentSimpleQuestionSeed(
        stable_key="present_simple_identify_01",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct Present Simple sentence.",
        question="Which sentence is correct?",
        options=[
            "He go to the gym on Mondays.",
            "He goes to the gym on Mondays.",
            "He going to the gym on Mondays.",
            "He does goes to the gym on Mondays.",
        ],
        correct_answer="He goes to the gym on Mondays.",
        accepted_answers=[],
        explanation="With he, the affirmative verb needs -s/-es: goes.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_identify_02",
        topic="identify",
        question_type="multiple_choice",
        instruction="Identify the correct negative sentence.",
        question="Which sentence is correct?",
        options=[
            "She don't works here.",
            "She doesn't works here.",
            "She doesn't work here.",
            "She not works here.",
        ],
        correct_answer="She doesn't work here.",
        accepted_answers=[],
        explanation="After doesn't, use the base form work without -s.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_identify_03",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct question.",
        question="Which question is correct?",
        options=[
            "Does they watch movies on Friday?",
            "Do they watches movies on Friday?",
            "Do they watch movies on Friday?",
            "They do watch movies on Friday?",
        ],
        correct_answer="Do they watch movies on Friday?",
        accepted_answers=[],
        explanation="Use Do with they + base verb watch.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_identify_04",
        topic="identify",
        question_type="identify",
        instruction="Identify the sentence with the correct third-person -s.",
        question="Which sentence uses the third person correctly?",
        options=[
            "My dad teach math.",
            "My dad teaches math.",
            "My dad teaching math.",
            "My dad do teach math.",
        ],
        correct_answer="My dad teaches math.",
        accepted_answers=[],
        explanation=(
            "Teach ends in -ch, so add -es for he/she/it: teaches."
        ),
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_identify_05",
        topic="identify",
        question_type="multiple_choice",
        instruction="Identify the correct short answer.",
        question="Does it rain a lot in April?",
        options=[
            "Yes, it do.",
            "Yes, it rains.",
            "Yes, it does.",
            "Yes, it is.",
        ],
        correct_answer="Yes, it does.",
        accepted_answers=[],
        explanation="For it, the affirmative short answer is Yes, it does.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_identify_06",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct affirmative sentence.",
        question="Which sentence is correct?",
        options=[
            "We lives in a small town.",
            "We live in a small town.",
            "We living in a small town.",
            "We does live in a small town.",
        ],
        correct_answer="We live in a small town.",
        accepted_answers=[],
        explanation="With we, use the base form live (no -s).",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_identify_07",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct negative sentence.",
        question="Which sentence is correct?",
        options=[
            "I doesn't like onions.",
            "I don't likes onions.",
            "I don't like onions.",
            "I not like onions.",
        ],
        correct_answer="I don't like onions.",
        accepted_answers=[],
        explanation="With I, use don't + base verb like.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_identify_08",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct question.",
        question="Which question is correct?",
        options=[
            "Does your sister plays tennis?",
            "Do your sister play tennis?",
            "Does your sister play tennis?",
            "Your sister does play tennis?",
        ],
        correct_answer="Does your sister play tennis?",
        accepted_answers=[],
        explanation="Your sister is she, so use Does + base verb play.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_identify_09",
        topic="identify",
        question_type="multiple_choice",
        instruction="Identify the sentence with the correct verb form.",
        question="Which sentence is correct?",
        options=[
            "She flys to Madrid every summer.",
            "She flies to Madrid every summer.",
            "She fly to Madrid every summer.",
            "She flying to Madrid every summer.",
        ],
        correct_answer="She flies to Madrid every summer.",
        accepted_answers=[],
        explanation="For consonant + y, change y to i and add -es: fly → flies.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_identify_10",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct negative sentence.",
        question="Which sentence is correct?",
        options=[
            "He don't watch TV.",
            "He doesn't watches TV.",
            "He doesn't watch TV.",
            "He not watch TV.",
        ],
        correct_answer="He doesn't watch TV.",
        accepted_answers=[],
        explanation="With he, use doesn't + base verb watch.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_identify_11",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct short answer.",
        question="Do they speak English?",
        options=[
            "Yes, they does.",
            "Yes, they speak.",
            "Yes, they do.",
            "Yes, they are.",
        ],
        correct_answer="Yes, they do.",
        accepted_answers=[],
        explanation="An affirmative short answer for they uses do.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_identify_12",
        topic="identify",
        question_type="identify",
        instruction="Identify the correct affirmative sentence.",
        question="Which sentence is correct?",
        options=[
            "The bus leave at noon.",
            "The bus leaves at noon.",
            "The bus leaving at noon.",
            "The bus do leave at noon.",
        ],
        correct_answer="The bus leaves at noon.",
        accepted_answers=[],
        explanation="The bus is it, so add -s: leaves.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_identify_13",
        topic="identify",
        question_type="multiple_choice",
        instruction="Identify the correct question.",
        question="Which question is correct?",
        options=[
            "Do she work here?",
            "Does she works here?",
            "Does she work here?",
            "She does work here?",
        ],
        correct_answer="Does she work here?",
        accepted_answers=[],
        explanation="Use Does + she + base verb work.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_identify_14",
        topic="identify",
        question_type="identify",
        instruction="Identify the sentence that uses don't/doesn't correctly.",
        question="Which sentence is correct?",
        options=[
            "We doesn't go shopping on Mondays.",
            "We don't go shopping on Mondays.",
            "We don't goes shopping on Mondays.",
            "We not go shopping on Mondays.",
        ],
        correct_answer="We don't go shopping on Mondays.",
        accepted_answers=[],
        explanation="With we, use don't + base verb go.",
    ),
    # Ordenar palabras
    PresentSimpleQuestionSeed(
        stable_key="present_simple_order_words_01",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="she / does / play / tennis",
        options=None,
        correct_answer="Does she play tennis?",
        accepted_answers=[],
        explanation="Place does before the subject, then use the base verb play.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_order_words_02",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make an affirmative sentence.",
        question="every morning / breakfast / eats / he",
        options=None,
        correct_answer="He eats breakfast every morning.",
        accepted_answers=[],
        explanation=(
            "Subject + verb with -s + object + time expression: He eats breakfast every morning."
        ),
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_order_words_03",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make a negative sentence.",
        question="like / don't / spicy food / they",
        options=None,
        correct_answer="They don't like spicy food.",
        accepted_answers=["They do not like spicy food."],
        explanation="Subject + don't + base verb + object.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_order_words_04",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="do / your friends / to school / walk",
        options=None,
        correct_answer="Do your friends walk to school?",
        accepted_answers=[],
        explanation="Use Do + plural subject + base verb.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_order_words_05",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make an affirmative sentence.",
        question="watches / after dinner / TV / Laura",
        options=None,
        correct_answer="Laura watches TV after dinner.",
        accepted_answers=[],
        explanation="Laura is she, so use watches (third person -es).",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_order_words_06",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="live / does / near here / he",
        options=None,
        correct_answer="Does he live near here?",
        accepted_answers=[],
        explanation="Place does before the subject he, then the base verb live.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_order_words_07",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make a negative sentence.",
        question="doesn't / coffee / drink / she",
        options=None,
        correct_answer="She doesn't drink coffee.",
        accepted_answers=["She does not drink coffee."],
        explanation="Subject + doesn't + base verb + object.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_order_words_08",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make an affirmative sentence.",
        question="English / speak / we / at home",
        options=None,
        correct_answer="We speak English at home.",
        accepted_answers=[],
        explanation="With we, use the base form speak: We speak English at home.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_order_words_09",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="do / like / you / chocolate",
        options=None,
        correct_answer="Do you like chocolate?",
        accepted_answers=[],
        explanation="Use Do + you + base verb like.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_order_words_10",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make a negative sentence.",
        question="don't / on Sundays / work / I",
        options=None,
        correct_answer="I don't work on Sundays.",
        accepted_answers=["I do not work on Sundays."],
        explanation="Subject + don't + base verb + time expression.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_order_words_11",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make an affirmative sentence.",
        question="to school / goes / by bus / my brother",
        options=None,
        correct_answer="My brother goes to school by bus.",
        accepted_answers=[],
        explanation="My brother is he, so use goes.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_order_words_12",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="the piano / play / does / Anna",
        options=None,
        correct_answer="Does Anna play the piano?",
        accepted_answers=[],
        explanation="Place does before Anna, then the base verb play.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_order_words_13",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make a negative sentence.",
        question="meat / eat / doesn't / Tom",
        options=None,
        correct_answer="Tom doesn't eat meat.",
        accepted_answers=["Tom does not eat meat."],
        explanation="Subject + doesn't + base verb eat + object.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_order_words_14",
        topic="order_words",
        question_type="order_words",
        instruction="Order the words to make a question.",
        question="work / do / in a hospital / they",
        options=None,
        correct_answer="Do they work in a hospital?",
        accepted_answers=[],
        explanation="Use Do + they + base verb work.",
    ),
    # Oraciones
    PresentSimpleQuestionSeed(
        stable_key="present_simple_sentences_01",
        topic="sentences",
        question_type="transform_sentence",
        instruction=(
            "Rewrite the sentence in the Present Simple affirmative "
            "with the correct verb form."
        ),
        question="(My cousins / visit) us on weekends.",
        options=None,
        correct_answer="My cousins visit us on weekends.",
        accepted_answers=["My cousins visit us on weekends"],
        explanation="Cousins is they, so use the base form visit (no -s).",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_sentences_02",
        topic="sentences",
        question_type="transform_sentence",
        instruction="Change the affirmative sentence into a negative sentence.",
        question="We finish homework before dinner.",
        options=None,
        correct_answer="We don't finish homework before dinner.",
        accepted_answers=[
            "We do not finish homework before dinner.",
            "We don't finish homework before dinner",
        ],
        explanation="Use don't + base verb finish with we.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_sentences_03",
        topic="sentences",
        question_type="transform_sentence",
        instruction="Change the sentence into a Present Simple question.",
        question="The dog sleeps on the sofa.",
        options=None,
        correct_answer="Does the dog sleep on the sofa?",
        accepted_answers=[],
        explanation=(
            "The dog is it, so use Does + subject + base verb sleep."
        ),
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_sentences_04",
        topic="sentences",
        question_type="fill_blank",
        instruction=(
            "Complete the sentence with the correct Present Simple form "
            "of the verb in parentheses."
        ),
        question="Carla ___ her room every Saturday. (clean)",
        options=None,
        correct_answer="cleans",
        accepted_answers=[],
        explanation="Carla is she, so clean becomes cleans.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_sentences_05",
        topic="sentences",
        question_type="multiple_choice",
        instruction="Choose the sentence that correctly uses the Present Simple.",
        question="Which sentence is correct?",
        options=[
            "Does Peter likes pizza?",
            "Peter like pizza.",
            "Peter likes pizza.",
            "Peter liking pizza.",
        ],
        correct_answer="Peter likes pizza.",
        accepted_answers=[],
        explanation=(
            "Affirmative with he uses likes. In questions, use Does + like (base form)."
        ),
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_sentences_06",
        topic="sentences",
        question_type="transform_sentence",
        instruction="Rewrite the sentence in the Present Simple affirmative.",
        question="(she / teach) English at the high school.",
        options=None,
        correct_answer="She teaches English at the high school.",
        accepted_answers=["She teaches English at the high school"],
        explanation="With she, teach becomes teaches (add -es after ch).",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_sentences_07",
        topic="sentences",
        question_type="transform_sentence",
        instruction="Change the affirmative sentence into a negative sentence.",
        question="He reads comics after lunch.",
        options=None,
        correct_answer="He doesn't read comics after lunch.",
        accepted_answers=[
            "He does not read comics after lunch.",
            "He doesn't read comics after lunch",
        ],
        explanation="Use doesn't + base verb read. Remove the -s from reads.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_sentences_08",
        topic="sentences",
        question_type="transform_sentence",
        instruction="Change the sentence into a Present Simple question.",
        question="They buy groceries on Saturdays.",
        options=None,
        correct_answer="Do they buy groceries on Saturdays?",
        accepted_answers=[],
        explanation="Use Do + they + base verb buy.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_sentences_09",
        topic="sentences",
        question_type="fill_blank",
        instruction="Complete the sentence with the correct Present Simple form.",
        question="My parents ___ breakfast together. (have)",
        options=None,
        correct_answer="have",
        accepted_answers=[],
        explanation="My parents is they, so use the base form have.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_sentences_10",
        topic="sentences",
        question_type="multiple_choice",
        instruction="Choose the correct sentence.",
        question="Which sentence is correct?",
        options=[
            "She don't go to bed early.",
            "She doesn't goes to bed early.",
            "She doesn't go to bed early.",
            "She not go to bed early.",
        ],
        correct_answer="She doesn't go to bed early.",
        accepted_answers=[],
        explanation="Use doesn't + base verb go with she.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_sentences_11",
        topic="sentences",
        question_type="transform_sentence",
        instruction="Rewrite the sentence in the Present Simple affirmative.",
        question="(the sun / rise) in the east.",
        options=None,
        correct_answer="The sun rises in the east.",
        accepted_answers=["The sun rises in the east"],
        explanation="The sun is it, so rise becomes rises.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_sentences_12",
        topic="sentences",
        question_type="fill_blank",
        instruction="Complete the sentence with don't or doesn't and the base verb.",
        question="I ___ soccer on Tuesdays. (play)",
        options=None,
        correct_answer="don't play",
        accepted_answers=["do not play"],
        explanation="With I, use don't + base verb play.",
    ),
    PresentSimpleQuestionSeed(
        stable_key="present_simple_sentences_13",
        topic="sentences",
        question_type="transform_sentence",
        instruction="Change the sentence into a Present Simple question.",
        question="Your uncle works in a bank.",
        options=None,
        correct_answer="Does your uncle work in a bank?",
        accepted_answers=[],
        explanation="Your uncle is he, so use Does + base verb work.",
    ),
]
